import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";

/**
 * The e2e mock returns the shapes Rust actually returns.
 *
 * `e2e/tauri-mock.ts` stubs `window.__TAURI_INTERNALS__` so 100 Playwright
 * tests can drive the real frontend with no backend. Every one of them is
 * only as truthful as that stub: the table is typed
 * `Record<string, unknown>`, so a shape can drift from its Rust struct
 * without tsc noticing.
 *
 * The drift is quiet in the direction that matters. Add a field to a Rust
 * struct and the mock keeps serving the old object; the app reads
 * `undefined`, React renders nothing where a number belongs, and the e2e run
 * stays green — while the packaged build shows the new field. The suite
 * would be certifying a version of the backend that no longer exists.
 *
 * Only the two commands whose mock value is a literal OBJECT are checked.
 * Scalars and functions have nothing to compare, and the deliberately
 * unlisted commands null-resolve by design (the mock's own header explains
 * that choice). This is not "the mock matches the whole IPC surface" — it is
 * the two places where a struct and a hand-written literal have to agree.
 *
 * The bindings are ts-rs output, regenerated by `cargo test --lib`, so the
 * Rust side of this comparison cannot be stale without CI failing first.
 */

const ROOT = resolve(__dirname, "../..");
const mock = readFileSync(join(ROOT, "e2e/tauri-mock.ts"), "utf8");

/** Top-level field names of a generated `export type X = { … }` binding. */
function bindingFields(name: string): string[] {
  const src = readFileSync(join(ROOT, "src/bindings", `${name}.ts`), "utf8");
  const body = new RegExp(`export type ${name} = \\{([\\s\\S]*)\\};`).exec(src);
  if (!body) return [];
  // Strip doc comments, then take `name:` at nesting depth 0.
  const clean = body[1].replace(/\/\*[\s\S]*?\*\//g, "");
  const out: string[] = [];
  let depth = 0;
  for (const m of clean.matchAll(/[{}]|(\w+)\s*:/g)) {
    if (m[0] === "{") depth++;
    else if (m[0] === "}") depth--;
    else if (depth === 0 && m[1]) out.push(m[1]);
  }
  return [...new Set(out)].sort();
}

/** Keys of a one-line object literal in the mock's command table. */
function mockFields(command: string): string[] {
  const m = new RegExp(`\\n\\s*${command}: \\{([^}]*)\\}`).exec(mock);
  if (!m) return [];
  return [...new Set([...m[1].matchAll(/(\w+):/g)].map((x) => x[1]))].sort();
}

const PAIRS: Array<{ command: string; binding: string }> = [
  { command: "get_cache_stats", binding: "CacheStats" },
  { command: "get_warm_start", binding: "WarmStart" },
  { command: "session_state", binding: "SessionState" },
];

describe("the e2e mock's object shapes", () => {
  it("found both sides of every pair", () => {
    // A comparison of two empty lists passes forever, which is how four
    // checks in this repo once reported success while scanning nothing.
    for (const { command, binding } of PAIRS) {
      expect(mockFields(command).length, `no mock literal parsed for ${command}`)
        .toBeGreaterThan(2);
      expect(bindingFields(binding).length, `no fields parsed out of ${binding}.ts`)
        .toBeGreaterThan(2);
    }
  });

  for (const { command, binding } of PAIRS) {
    it(`${command} returns exactly the fields of ${binding}`, () => {
      // Both directions matter. A field the mock is MISSING renders as
      // undefined in every e2e run; a field it INVENTS is a shape the backend
      // never sends, so a test can pass on data that cannot occur.
      expect(mockFields(command)).toEqual(bindingFields(binding));
    });
  }
});
