/**
 * Stable per-install identity (r124).
 *
 * Session member ids (m0, m1, ...) are minted by the host at Hello. Minting
 * unconditionally meant a friend who dropped and rejoined came back as a
 * SECOND member: same human, fresh id, roster grew, and the abandoned tile
 * sat on "Connecting" forever. This id lets the host recognise a returning
 * install and hand back the SAME member id.
 *
 * Scope: one value per app install, shared only with session members (never
 * a network service). It is not an account, carries no personal data, and is
 * regenerated by clearing app data.
 */

const INSTALL_ID_KEY = "saucebunny.installId";

export function loadInstallId(): string {
  try {
    const existing = localStorage.getItem(INSTALL_ID_KEY);
    if (existing) return existing;
    const fresh = crypto.randomUUID();
    localStorage.setItem(INSTALL_ID_KEY, fresh);
    return fresh;
  } catch {
    // Private mode / quota: fall back to a per-run id. A rejoin inside the
    // same run still reclaims; across runs it mints, which is the old
    // behaviour rather than a regression.
    return crypto.randomUUID();
  }
}
