// @ts-check
/**
 * TWO RULES, on purpose.
 *
 * This codebase is built almost entirely out of long-lived listeners reading
 * hand-mirrored refs, so a wrong dependency array is not a style nit - it is a
 * stale-closure bug that only shows up in a live two-machine session. Those
 * two rules are the only automated defense against that, and they are the
 * whole reason this config exists.
 *
 * No style rules, no formatting rules, no opinionated presets. They would
 * fight the house conventions in CLAUDE.md, produce hundreds of warnings
 * nobody reads, and the usual outcome is that the entire linter gets disabled.
 * A linter that runs and is trusted beats a thorough one that gets turned off.
 *
 * Note: 38 `eslint-disable` comments predated this file - they suppressed a
 * linter that was never installed. `reportUnusedDisableDirectives` is on so
 * the ones that no longer suppress anything get deleted rather than accreting.
 */
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";

export default [
  {
    ignores: [
      "dist/**",
      "src-tauri/**",
      "node_modules/**",
      "src/bindings/**", // generated by ts-rs; cargo test --lib owns these
    ],
  },
  {
    files: ["src/**/*.{ts,tsx}", "e2e/**/*.ts"],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      "react-hooks": reactHooks,
      // Registered but with NO rules enabled. Several files carry
      // `eslint-disable-next-line @typescript-eslint/no-explicit-any` from
      // before this config existed; without the plugin registered those
      // comments fail as "Definition for rule was not found" — an error about
      // a comment, not about code. Registering it makes them inert instead.
      "@typescript-eslint": tseslint.plugin,
    },
    linterOptions: {
      reportUnusedDisableDirectives: "warn",
    },
    rules: {
      // The whole point. rules-of-hooks is never a false positive - a
      // conditional hook IS a bug - so it is an error.
      "react-hooks/rules-of-hooks": "error",
      // exhaustive-deps has legitimate exceptions (a deliberately once-only
      // mount effect), so it warns and is silenced case by case WITH a reason.
      "react-hooks/exhaustive-deps": "warn",
      //
      // js.configs.recommended is deliberately NOT spread in here. It was
      // tried: it produced 17 errors and every single one was correct code -
      // no-control-regex on the filename and marker sanitizers that strip
      // control characters ON PURPOSE, no-irregular-whitespace on a literal
      // BOM in an SRT strip, no-useless-assignment on harmless initializers.
      // Zero bugs, 17 errors. That is the ratio that gets a linter deleted.
    },
  },
];
