//! Subprocess supervision with the actual raw actor and a link-time fake SDK.
//! Generated bytes and anonymous descriptors only; no OBS, NDI runtime, capture,
//! global service client, or network. These are ordinary (not ignored) tests.
use super::{BroadcastFailure, BroadcastHandle, BroadcastStatus, CleanupProof, SenderRuntime, StatusReader};
use super::super::raw_control::{Op, Reason, Wire};
use super::super::raw_service::{self, RawGenerations, RawStatus, tests::{Fixture, Peer}};
use std::{
    fs,
    os::{fd::{AsRawFd, FromRawFd, OwnedFd}, unix::fs::PermissionsExt},
    path::{Path, PathBuf},
    process::{Command, Stdio},
    sync::{Arc, OnceLock, atomic::Ordering},
    time::Duration,
};
use tokio::{sync::watch, time::timeout};

const DEADLINE: Duration = Duration::from_secs(12);
const CONTROL_WAIT: Duration = Duration::from_secs(1);
// Start is gated by native exec and SDK Ready, unlike a raw-only actor request.
// Retain production's startup limit plus the existing control delivery budget;
// a production Stopping/Failed status fails the wait immediately, not at this cap.
const START_WAIT: Duration = super::SDK_WAIT.saturating_add(CONTROL_WAIT);

struct Files { root: PathBuf }
impl Files {
    fn new() -> Self {
        let root = std::env::temp_dir().join(format!("sauce-broadcast-test-{}", uuid::Uuid::new_v4()));
        fs::create_dir(&root).unwrap();
        fs::set_permissions(&root, fs::Permissions::from_mode(0o700)).unwrap();
        Self { root }
    }
    fn executable(&self, name: &str, bytes: &[u8]) -> PathBuf {
        let path = self.root.join(name);
        fs::write(&path, bytes).unwrap();
        fs::set_permissions(&path, fs::Permissions::from_mode(0o700)).unwrap();
        path
    }
}
impl Drop for Files {
    fn drop(&mut self) { fs::remove_dir_all(&self.root).unwrap(); }
}

fn fake_binary() -> &'static [u8] {
    static COMPILED: OnceLock<Vec<u8>> = OnceLock::new();
    COMPILED.get_or_init(|| {
        let files = Files::new();
        let native = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("native");
        let executable = files.root.join("fake-sdk-sender");
        let diagnostics = files.root.join("compiler.log");
        let mut compiler = Command::new("/usr/bin/clang++")
            .args(["-std=c++17", "-Wall", "-Wextra", "-Werror", "-pthread"])
            .arg(native.join("ndi_sender_main.cpp"))
            .arg(native.join("ndi_sender.cpp"))
            .arg(native.join("ndi_sender_fake_sdk.cpp"))
            // Deliberately NEVER link ndi_sender_sdk.cpp or a vendor library.
            .arg("-o").arg(&executable)
            .stdin(Stdio::null()).stdout(Stdio::null())
            .stderr(fs::File::create(&diagnostics).unwrap()).spawn().unwrap();
        let deadline = std::time::Instant::now() + Duration::from_secs(30);
        let result = loop {
            if let Some(result) = compiler.try_wait().unwrap() { break result; }
            if std::time::Instant::now() >= deadline {
                let _ = compiler.kill(); let _ = compiler.wait();
                panic!("fake sender compilation timed out: {}", fs::read_to_string(&diagnostics).unwrap());
            }
            std::thread::sleep(Duration::from_millis(10));
        };
        assert!(result.success(), "{}", fs::read_to_string(&diagnostics).unwrap());
        // Keep only bytes in OnceLock, not a leaked temporary directory. Each
        // test gets a private executable and removes it after its child exits.
        fs::read(executable).unwrap()
    }).as_slice()
}

struct Case {
    fixture: Fixture,
    handle: BroadcastHandle,
    status: watch::Receiver<BroadcastStatus>,
    raw: watch::Receiver<RawStatus>,
    expected: RawGenerations,
    _files: Files,
}
impl Case {
    async fn new(mode: &str) -> Self {
        // Compile before starting the current-thread raw actor: a first-run
        // compiler invocation must not consume its handshake deadline.
        let bytes = fake_binary();
        let files = Files::new();
        let executable = files.executable("fake-sdk-sender", bytes);
        let runtime = SenderRuntime { sdk: executable.clone(), executable, fake_mode: Some(mode.into()) };
        Self::with_runtime(runtime, files).await
    }
    async fn with_runtime(runtime: SenderRuntime, files: Files) -> Self {
        let fixture = Fixture::new();
        let feed = raw_service::prepare(&fixture.program.id, &fixture.requests).unwrap();
        let raw = feed.status();
        let mut generations = feed.generations();
        fixture.peer.hello().await;
        let expected = timeout(Duration::from_secs(1), generations.wait_for(Option::is_some)).await.unwrap().unwrap().unwrap();
        fixture.peer.no_message().await; // Reservation alone never submits Start.
        let handle = super::launch(feed, runtime).unwrap();
        let status = handle.status();
        Self { fixture, handle, status, raw, expected, _files: files }
    }
    async fn start(&self) -> (Wire, OwnedFd) {
        let (record, mut writers) = receive_control(&self.fixture.peer, &self.status, &self.raw,
            || self.handle.child_pid(), Op::Start).await;
        assert_eq!(record.op, Op::Start);
        assert_eq!((record.capture, record.broadcast), (self.expected.capture, self.expected.broadcast));
        assert_eq!(writers.len(), 1, "one fresh write descriptor per attempt");
        self.fixture.peer.send(Wire { op: Op::Started, ..record }).await;
        wait_raw(&self.raw, |status| matches!(status, RawStatus::Live)).await;
        (record, writers.pop().unwrap())
    }
    async fn stop_request(&self, started: Wire) {
        let (record, descriptors) = receive_control(&self.fixture.peer, &self.status, &self.raw,
            || self.handle.child_pid(), Op::Stop).await;
        assert_eq!(record, Wire { op: Op::Stop, ..started });
        assert!(descriptors.is_empty());
    }
    async fn acknowledge_stop(&self, started: Wire) {
        self.fixture.peer.send(Wire { op: Op::Stopped, reason: Reason::Cancelled, ..started }).await;
    }
    fn preview_healthy(&self) {
        assert!(!self.fixture.program.is_stopped(), "broadcast cleanup must not stop Preview");
        assert!(self.fixture.program.encoded_ready());
    }
    async fn pid(&self) -> u32 {
        timeout(Duration::from_secs(2), async {
            loop {
                if let Some(pid) = self.handle.child_pid() { return pid; }
                tokio::time::sleep(Duration::from_millis(10)).await;
            }
        }).await.expect("sender child was never spawned")
    }
}

async fn receive_control(peer: &Peer, status: &watch::Receiver<BroadcastStatus>, raw: &watch::Receiver<RawStatus>,
                         pid: impl Fn() -> Option<u32>, op: Op) -> (Wire, Vec<OwnedFd>) {
    let began = std::time::Instant::now();
    let test = std::thread::current().name().unwrap_or("broadcast fixture").to_owned();
    let context = || format!("test={test}, pid={:?}, phase={op:?}", pid());
    let mut status = status.clone();
    let mut raw = raw.clone();
    let mut history = vec![(began.elapsed(), *status.borrow_and_update(), *raw.borrow_and_update())];
    let receive = peer.receive_within(if op == Op::Start { START_WAIT } else { CONTROL_WAIT });
    tokio::pin!(receive);
    let old_start_limit = tokio::time::sleep(CONTROL_WAIT);
    tokio::pin!(old_start_limit);
    let mut reported_old_limit = op != Op::Start;
    loop {
        assert!(op != Op::Start || matches!(*status.borrow(), BroadcastStatus::Starting),
            "sender left startup before raw Start: {}, history={history:?}", context());
        tokio::select! {
            result = &mut receive => {
                let record = result.unwrap_or_else(|error| panic!(
                    "control wait failed: {}, elapsed={:?}, error={error}, history={history:?}", context(), began.elapsed()));
                assert_eq!(record.0.op, op, "unexpected control: {}, history={history:?}", context());
                if reported_old_limit && op == Op::Start {
                    eprintln!("raw Start after {:?}: {}, history={history:?}", began.elapsed(), context());
                }
                return record;
            },
            changed = status.changed() => {
                assert!(changed.is_ok(), "broadcast status closed: {}, history={history:?}", context());
                history.push((began.elapsed(), *status.borrow_and_update(), *raw.borrow()));
            },
            changed = raw.changed() => {
                assert!(changed.is_ok(), "raw status closed: {}, history={history:?}", context());
                history.push((began.elapsed(), *status.borrow(), *raw.borrow_and_update()));
            },
            _ = &mut old_start_limit, if !reported_old_limit => {
                reported_old_limit = true;
                eprintln!("sender startup exceeded raw-only control budget: {}, history={history:?}", context());
            },
        }
    }
}

async fn wait_raw(status: &watch::Receiver<RawStatus>, predicate: impl Fn(&RawStatus) -> bool) -> RawStatus {
    let mut status = status.clone();
    let value = *timeout(DEADLINE, status.wait_for(predicate)).await.expect("raw actor deadline").expect("raw status closed");
    value
}
fn is_terminal(status: &BroadcastStatus) -> bool {
    matches!(status, BroadcastStatus::Stopped | BroadcastStatus::Failed { .. })
}
async fn terminal(status: &watch::Receiver<BroadcastStatus>) -> BroadcastStatus {
    let mut status = status.clone();
    let value = *timeout(DEADLINE, status.wait_for(is_terminal)).await.expect("broadcast cleanup deadline")
        .expect("broadcast status closed without a terminal state");
    value
}
async fn live(status: &watch::Receiver<BroadcastStatus>) {
    let mut status = status.clone();
    let value = *timeout(Duration::from_secs(2), status.wait_for(|value| matches!(value, BroadcastStatus::Live) || is_terminal(value)))
        .await.expect("sender did not become Live").expect("sender status closed");
    assert!(matches!(value, BroadcastStatus::Live), "{value:?}");
}
fn assert_reaped(pid: u32) {
    assert_eq!(unsafe { libc::kill(pid as libc::pid_t, 0) }, -1, "sender {pid} still exists after terminal cleanup");
    assert_eq!(std::io::Error::last_os_error().raw_os_error(), Some(libc::ESRCH));
}
fn failed_proof(status: BroadcastStatus) -> CleanupProof {
    match status {
        BroadcastStatus::Failed { cleanup, .. } => cleanup,
        status => panic!("expected a truthful Failed state, got {status:?}"),
    }
}
fn assert_complete(status: BroadcastStatus) {
    match status {
        BroadcastStatus::Stopped => {},
        BroadcastStatus::Failed { cleanup, .. } => assert!(cleanup.complete(), "{cleanup:?}"),
        status => panic!("cleanup was not terminal: {status:?}"),
    }
}

fn frame(record: Wire, kind: u8, timestamp: u64) -> Vec<u8> {
    let mut bytes = vec![0; 80];
    bytes[..4].copy_from_slice(b"SBR1"); bytes[4] = kind;
    bytes[8..16].copy_from_slice(&record.capture.to_be_bytes());
    bytes[16..24].copy_from_slice(&record.broadcast.to_be_bytes());
    bytes[24..32].copy_from_slice(&timestamp.to_be_bytes());
    bytes[32..36].copy_from_slice(&16u32.to_be_bytes());
    if kind == 1 {
        bytes[36..40].copy_from_slice(&2u32.to_be_bytes());
        bytes[40..44].copy_from_slice(&2u32.to_be_bytes());
        bytes[44..48].copy_from_slice(&8u32.to_be_bytes());
        for (index, byte) in bytes[64..].iter_mut().enumerate() { *byte = index as u8; }
    } else {
        bytes[48..52].copy_from_slice(&2u32.to_be_bytes());
        bytes[52..56].copy_from_slice(&48_000u32.to_be_bytes());
        bytes[56..58].copy_from_slice(&2u16.to_be_bytes());
        for (index, value) in [0.25f32, 0.5, -0.25, -0.5].into_iter().enumerate() {
            bytes[64 + index * 4..68 + index * 4].copy_from_slice(&value.to_le_bytes());
        }
    }
    bytes
}
fn write_bytes(writer: &OwnedFd, bytes: &[u8]) {
    assert!(bytes.len() <= 512);
    assert_eq!(unsafe { libc::write(writer.as_raw_fd(), bytes.as_ptr().cast(), bytes.len()) }, bytes.len() as isize,
        "generated raw fixture write failed: {}", std::io::Error::last_os_error());
}
fn write_av(writer: &OwnedFd, record: Wire) {
    let mut bytes = frame(record, 1, 1_000_000_000);
    bytes.extend(frame(record, 2, 1_000_000_000));
    write_bytes(writer, &bytes);
}

#[tokio::test]
async fn broadcast_live_requires_sender_and_raw_start_then_stop_reaps_every_owner() {
    let case = Case::new("normal").await;
    let (record, writer) = case.start().await;
    assert!(matches!(*case.status.borrow(), BroadcastStatus::Starting), "a raw Started ACK alone is not Live");
    let pid = case.pid().await;
    write_av(&writer, record); live(&case.status).await;
    case.handle.cancel(); case.stop_request(record).await;
    drop(writer); case.acknowledge_stop(record).await;
    timeout(DEADLINE, case.handle.stop()).await.unwrap().unwrap();
    assert!(matches!(*case.status.borrow(), BroadcastStatus::Stopped));
    timeout(Duration::from_secs(1), case.handle.stop()).await.unwrap().unwrap();
    assert_reaped(pid); case.preview_healthy();
    case.fixture.close().await;
}

#[tokio::test]
async fn broadcast_cancel_before_sender_ready_never_transfers_raw_writer() {
    let case = Case::new("block_create").await;
    let pid = case.pid().await;
    case.fixture.peer.no_message().await;
    assert!(matches!(*case.status.borrow(), BroadcastStatus::Starting));
    case.handle.cancel();
    assert!(matches!(wait_raw(&case.raw, |value| matches!(value, RawStatus::Stopped { .. })).await,
        RawStatus::Stopped { reason: Reason::Cancelled }));
    // Cancellation may reach the child before or during the foreign factory.
    // Both paths need complete barriers, never a speculative successful stop.
    assert_complete(terminal(&case.status).await);
    assert_reaped(pid); case.fixture.peer.no_message().await;
    case.preview_healthy(); case.fixture.close().await;
}

#[tokio::test]
async fn broadcast_start_wait_includes_explicitly_gated_sender_exec_before_ready() {
    let bytes = fake_binary();
    let files = Files::new();
    let sender = files.executable("fake-sdk-sender", bytes);
    let gate = files.root.join("exec-gate");
    let gate_name = std::ffi::CString::new(gate.as_os_str().as_encoded_bytes()).unwrap();
    assert_eq!(unsafe { libc::mkfifo(gate_name.as_ptr(), 0o600) }, 0);
    // No sleeps or child helpers in this wrapper: the test owns the FIFO gate,
    // and exec preserves the supervised PID and every production argument.
    let script = format!("#!/bin/sh\nIFS= read -r ignored < '{}'\nexec '{}' \"$@\"\n", gate.display(), sender.display());
    let executable = files.executable("gated-sender", script.as_bytes());
    let case = Case::with_runtime(SenderRuntime { executable, sdk: sender, fake_mode: Some("normal".into()) }, files).await;
    let release = timeout(START_WAIT, async {
        loop {
            let fd = unsafe { libc::open(gate_name.as_ptr(), libc::O_WRONLY | libc::O_NONBLOCK | libc::O_CLOEXEC) };
            if fd >= 0 { break unsafe { OwnedFd::from_raw_fd(fd) }; }
            assert_eq!(std::io::Error::last_os_error().raw_os_error(), Some(libc::ENXIO), "exec gate open failed");
            tokio::time::sleep(Duration::from_millis(10)).await;
        }
    }).await.expect("sender never opened its explicit exec gate");
    let pid = case.pid().await;
    let (record, writer) = {
        let start = case.start();
        tokio::pin!(start);
        // Opening the writer proves that this exact child has opened the reader.
        // Keep it there beyond the old fixture budget; no Ready/Start can exist yet.
        tokio::select! {
            record = &mut start => panic!("raw Start escaped the closed exec gate: {:?}", record.0),
            _ = tokio::time::sleep(CONTROL_WAIT + Duration::from_millis(100)) => {},
        }
        assert!(matches!(*case.status.borrow(), BroadcastStatus::Starting));
        assert!(matches!(*case.raw.borrow(), RawStatus::Starting));
        write_bytes(&release, b"release\n"); drop(release);
        start.await
    };
    write_av(&writer, record); live(&case.status).await;
    case.handle.cancel(); case.stop_request(record).await;
    drop(writer); case.acknowledge_stop(record).await;
    assert!(matches!(terminal(&case.status).await, BroadcastStatus::Stopped));
    assert_reaped(pid); case.preview_healthy();
    case.fixture.close().await;
}

#[tokio::test]
async fn broadcast_factory_that_never_becomes_ready_still_hits_production_startup_deadline() {
    let case = Case::new("block_create").await;
    let pid = case.pid().await;
    let ended = terminal(&case.status).await;
    assert!(matches!(ended, BroadcastStatus::Failed { reason: BroadcastFailure::StartupTimeout, cleanup }
        if cleanup.complete()), "{ended:?}");
    assert_reaped(pid);
    // Any premature Start remains queued here and fails this negative assertion.
    case.fixture.peer.no_message().await;
    assert!(matches!(*case.raw.borrow(), RawStatus::Stopped { .. }));
    case.preview_healthy(); case.fixture.close().await;
}

#[tokio::test]
async fn broadcast_handle_drop_still_cancels_raw_and_reaps_the_sender() {
    let case = Case::new("normal").await;
    let (record, writer) = case.start().await;
    let pid = case.pid().await;
    write_av(&writer, record); live(&case.status).await;
    let Case { fixture, handle, status, raw, _files, .. } = case;
    drop(handle);
    let (stop, descriptors) = receive_control(&fixture.peer, &status, &raw, || Some(pid), Op::Stop).await;
    assert_eq!(stop, Wire { op: Op::Stop, ..record }); assert!(descriptors.is_empty());
    drop(writer); fixture.peer.send(Wire { op: Op::Stopped, reason: Reason::Cancelled, ..record }).await;
    assert!(matches!(terminal(&status).await, BroadcastStatus::Stopped));
    assert_reaped(pid); assert!(fixture.program.encoded_ready()); assert!(!fixture.program.is_stopped());
    fixture.close().await;
}

#[tokio::test]
async fn broadcast_sdk_unavailable_cancels_its_unarmed_reservation_without_start() {
    let case = Case::new("unavailable").await;
    let pid = case.pid().await;
    assert!(failed_proof(terminal(&case.status).await).complete());
    assert_reaped(pid); case.fixture.peer.no_message().await;
    assert!(matches!(*case.raw.borrow(), RawStatus::Stopped { .. }));
    case.preview_healthy(); case.fixture.close().await;
}

#[tokio::test]
async fn broadcast_raw_stop_ack_cannot_substitute_for_an_open_pipe_eof() {
    let case = Case::new("normal").await;
    let (record, writer) = case.start().await;
    let pid = case.pid().await;
    write_av(&writer, record); live(&case.status).await;
    case.handle.cancel(); case.stop_request(record).await;
    // Deliberately adversarial helper: it claims Stopped while retaining its
    // writer. The child and standby reader cannot observe EOF from this ACK.
    case.acknowledge_stop(record).await;
    wait_raw(&case.raw, |value| matches!(value, RawStatus::Stopped { .. })).await;
    let cleanup = failed_proof(terminal(&case.status).await);
    assert!(cleanup.child_reaped && cleanup.raw_stopped);
    assert!(!cleanup.pipe_eof && !cleanup.complete());
    assert_reaped(pid); drop(writer);
    case.preview_healthy(); case.fixture.close().await;
}

#[tokio::test]
async fn broadcast_real_pipe_eof_cannot_substitute_for_missing_helper_ack() {
    let case = Case::new("normal").await;
    let (record, writer) = case.start().await;
    let pid = case.pid().await;
    write_av(&writer, record); live(&case.status).await;
    case.handle.cancel(); case.stop_request(record).await;
    drop(writer); // True EOF; deliberately withhold the native terminal ACK.
    let ended = terminal(&case.status).await;
    let cleanup = failed_proof(ended);
    assert!(cleanup.child_reaped && cleanup.pipe_eof);
    assert!(!cleanup.raw_stopped && !cleanup.complete());
    assert_reaped(pid);
    case.acknowledge_stop(record).await;
    wait_raw(&case.raw, |value| matches!(value, RawStatus::Stopped { .. })).await;
    assert_eq!(*case.status.borrow(), ended, "late ACK cannot resurrect a retired broadcast");
    case.preview_healthy(); case.fixture.close().await;
}

#[tokio::test]
async fn broadcast_malformed_generation_fails_sender_but_stops_only_its_raw_attempt() {
    let case = Case::new("normal").await;
    let (record, writer) = case.start().await;
    let pid = case.pid().await;
    let invalid = Wire { capture: record.capture + 1, ..record };
    write_bytes(&writer, &frame(invalid, 1, 1_000_000_000));
    case.stop_request(record).await;
    drop(writer); case.acknowledge_stop(record).await;
    let ended = terminal(&case.status).await;
    assert!(failed_proof(ended).complete(), "malformed input cleanup: pid={pid}, status={ended:?}, raw={:?}", *case.raw.borrow());
    assert_reaped(pid); case.preview_healthy(); case.fixture.close().await;
}

#[tokio::test]
async fn broadcast_source_loss_is_failure_with_complete_cleanup_not_a_preview_stop() {
    let case = Case::new("normal").await;
    let (record, writer) = case.start().await;
    let pid = case.pid().await;
    write_av(&writer, record); live(&case.status).await;
    case.fixture.captures.send_replace(Vec::new());
    case.stop_request(record).await;
    drop(writer);
    case.fixture.peer.send(Wire { op: Op::Failed, reason: Reason::SourceStopped, ..record }).await;
    assert!(failed_proof(terminal(&case.status).await).complete());
    assert_reaped(pid); case.preview_healthy(); case.fixture.close().await;
}

#[tokio::test]
async fn broadcast_blocked_sdk_destructor_requires_kill_and_still_proves_all_cleanup() {
    let case = Case::new("block_destroy").await;
    let (record, writer) = case.start().await;
    let pid = case.pid().await;
    write_av(&writer, record); live(&case.status).await; // The fake sink certainly exists.
    case.handle.cancel(); case.stop_request(record).await;
    drop(writer); case.acknowledge_stop(record).await;
    let ended = terminal(&case.status).await;
    assert!(matches!(ended, BroadcastStatus::Failed { reason: BroadcastFailure::ShutdownTimeout, .. }), "{ended:?}");
    assert!(failed_proof(ended).complete());
    assert_reaped(pid); case.preview_healthy(); case.fixture.close().await;
}

#[tokio::test]
async fn broadcast_blocked_sdk_send_times_out_without_ever_becoming_live() {
    let case = Case::new("block_audio").await;
    let (record, writer) = case.start().await;
    let pid = case.pid().await;
    write_av(&writer, record);
    // Do not race a manual signal against entry into the SDK call. Let the
    // supervisor's missing-Live deadline initiate the owned shutdown instead.
    let mut statuses = case.status.clone();
    let stop = async {
        loop {
            assert!(!matches!(*statuses.borrow_and_update(), BroadcastStatus::Live));
            if matches!(*statuses.borrow(), BroadcastStatus::Stopping) { break; }
            statuses.changed().await.expect("status closed before timeout cleanup");
        }
    };
    timeout(DEADLINE, stop).await.unwrap();
    case.stop_request(record).await;
    drop(writer); case.acknowledge_stop(record).await;
    let ended = terminal(&case.status).await;
    assert!(failed_proof(ended).complete(), "blocked audio cleanup: pid={pid}, status={ended:?}, raw={:?}", *case.raw.borrow());
    assert_reaped(pid); case.preview_healthy(); case.fixture.close().await;
}

#[tokio::test]
async fn broadcast_malformed_child_status_never_arms_the_raw_reservation() {
    let files = Files::new();
    // Builtins only: no shell descendants can outlive the supervised PID.
    let executable = files.executable("malformed-status", b"#!/bin/sh\nprintf 'not-json\\n'\nIFS= read -r ignored\n");
    let runtime = SenderRuntime { sdk: executable.clone(), executable, fake_mode: None };
    let case = Case::with_runtime(runtime, files).await;
    let pid = case.pid().await;
    assert!(failed_proof(terminal(&case.status).await).complete());
    assert_reaped(pid); case.fixture.peer.no_message().await;
    case.preview_healthy(); case.fixture.close().await;
}

#[test]
fn broadcast_status_reader_preserves_partial_lines_and_valid_state_order() {
    let mut reader = StatusReader::default();
    reader.push(b"{\"sta").unwrap();
    assert!(!reader.ready && !reader.live && reader.records == 0);
    reader.push(b"te\":\"ready\"}\n{\"state\":\"li").unwrap();
    assert!(reader.ready && !reader.live && reader.records == 1);
    reader.push(b"ve\"}\n{\"state\":\"stopping\"}\n").unwrap();
    assert!(reader.ready && reader.live && reader.stopping && reader.records == 3);
    assert!(reader.pending.is_empty());
    reader.push(b"{\"state\":\"failed\",\"reason\":\"sink_failed\"}\n").unwrap();
    assert_eq!(reader.failed, Some(BroadcastFailure::SinkFailed));
}

#[test]
fn broadcast_status_reader_rejects_unknown_fields_states_reasons_and_non_json() {
    for invalid in [
        b"\n".as_slice(), b"not-json\n", b"[]\n", b"null\n", b"\xff\n",
        b"{\"state\":\"stopped\"}\n", b"{\"state\":\"complete\"}\n",
        b"{\"state\":\"ready\",\"extra\":true}\n",
        b"{\"state\":\"ready\",\"reason\":\"sink_failed\"}\n",
        b"{\"state\":\"failed\"}\n", b"{\"state\":\"failed\",\"reason\":null}\n",
        b"{\"state\":\"failed\",\"reason\":\"arbitrary vendor text\"}\n",
        b"{\"state\":\"failed\",\"reason\":\"read_failed\",\"path\":\"private\"}\n",
    ] {
        assert_eq!(StatusReader::default().push(invalid), Err(BroadcastFailure::Protocol), "{:?}", String::from_utf8_lossy(invalid));
    }
}

#[test]
fn broadcast_status_reader_rejects_duplicate_or_late_ready_live_and_stopping() {
    for invalid in [
        b"{\"state\":\"live\"}\n".as_slice(),
        b"{\"state\":\"ready\"}\n{\"state\":\"ready\"}\n",
        b"{\"state\":\"ready\"}\n{\"state\":\"live\"}\n{\"state\":\"live\"}\n",
        b"{\"state\":\"stopping\"}\n{\"state\":\"ready\"}\n",
        b"{\"state\":\"ready\"}\n{\"state\":\"stopping\"}\n{\"state\":\"live\"}\n",
        b"{\"state\":\"stopping\"}\n{\"state\":\"stopping\"}\n",
        b"{\"state\":\"failed\",\"reason\":\"sdk_unavailable\"}\n{\"state\":\"ready\"}\n",
        b"{\"state\":\"ready\"}\n{\"state\":\"failed\",\"reason\":\"sink_failed\"}\n{\"state\":\"live\"}\n",
    ] {
        assert_eq!(StatusReader::default().push(invalid), Err(BroadcastFailure::Protocol));
    }
}

#[test]
fn broadcast_status_reader_enforces_exact_line_total_and_record_bounds() {
    const READY: &[u8] = b"{\"state\":\"ready\"}\n";
    const FAILED: &[u8] = b"{\"state\":\"failed\",\"reason\":\"read_failed\"}\n";
    let mut exact = vec![b' '; 256 - (READY.len() - 1)];
    exact.extend_from_slice(READY);
    let mut reader = StatusReader::default();
    reader.push(&exact).unwrap();
    assert!(reader.ready && reader.pending.is_empty());
    let mut excessive = vec![b' ']; excessive.extend_from_slice(&exact);
    assert_eq!(StatusReader::default().push(&excessive), Err(BroadcastFailure::Protocol));

    // Isolate the aggregate counter from the stricter line/record bounds.
    let mut total = StatusReader { total: 4096 - READY.len(), ..StatusReader::default() };
    total.push(READY).unwrap(); assert_eq!(total.total, 4096);
    assert_eq!(total.push(b" "), Err(BroadcastFailure::Protocol));
    let mut oversized_read = StatusReader::default();
    assert_eq!(oversized_read.push(&[b' '; 4097]), Err(BroadcastFailure::Protocol));
    assert!(oversized_read.pending.is_empty() && oversized_read.records == 0);

    let mut records = StatusReader::default();
    for _ in 0..8 { records.push(FAILED).unwrap(); }
    assert_eq!(records.records, 8);
    assert_eq!(records.push(FAILED), Err(BroadcastFailure::Protocol));
}

#[test]
fn broadcast_status_failures_are_closed_and_preserve_the_first_failure() {
    for (reason, expected) in [
        ("usage", BroadcastFailure::Protocol), ("invalid_input", BroadcastFailure::InputFailed),
        ("truncated_input", BroadcastFailure::InputFailed), ("read_failed", BroadcastFailure::InputFailed),
        ("sdk_unavailable", BroadcastFailure::SdkUnavailable), ("read_timeout", BroadcastFailure::ReadTimeout),
        ("sink_failed", BroadcastFailure::SinkFailed), ("drain_timeout", BroadcastFailure::DrainTimeout),
    ] {
        let mut reader = StatusReader::default();
        reader.push(format!("{{\"state\":\"failed\",\"reason\":\"{reason}\"}}\n").as_bytes()).unwrap();
        reader.push(b"{\"state\":\"failed\",\"reason\":\"read_failed\"}\n").unwrap();
        assert_eq!(reader.failed, Some(expected));
    }
}

#[test]
fn broadcast_cleanup_proof_requires_all_three_independent_barriers() {
    for mask in 0..8 {
        let proof = CleanupProof { child_reaped: mask & 1 != 0, raw_stopped: mask & 2 != 0, pipe_eof: mask & 4 != 0 };
        assert_eq!(proof.complete(), mask == 7, "{proof:?}");
    }
}

#[test]
fn broadcast_packaged_sender_candidate_never_uses_a_developer_override() {
    let executable = Path::new("/Applications/Generated App.app/Contents/MacOS/generated-app");
    let packaged = PathBuf::from("/Applications/Generated App.app/Contents/Helpers/NDISender.bundle/Contents/MacOS/saucebunny-ndi-sender");
    let outside = PathBuf::from("/private/tmp/generated-sender-override");
    for developer in [false, true] {
        for explicit in [None, Some(outside.clone())] {
            assert_eq!(super::sender_candidate(executable, developer, explicit), Some(packaged.clone()));
        }
    }
}

#[test]
fn broadcast_unbundled_sender_requires_an_explicit_developer_override() {
    let executable = Path::new("/private/tmp/generated-debug-build/generated-app");
    let explicit = PathBuf::from("/private/tmp/generated-sender-override");
    assert_eq!(super::sender_candidate(executable, true, Some(explicit.clone())), Some(explicit.clone()));
    assert_eq!(super::sender_candidate(executable, true, None), None);
    assert_eq!(super::sender_candidate(executable, false, Some(explicit.clone())), None);
    assert_eq!(super::sender_candidate(executable, false, None), None);
    assert_eq!(super::sender_candidate(Path::new("/"), true, Some(explicit)), None);
}

#[test]
fn broadcast_permit_cancellation_does_not_admit_a_duplicate_or_cancel_another_id() {
    let id = uuid::Uuid::new_v4().simple().to_string();
    let other_id = uuid::Uuid::new_v4().simple().to_string();
    let first = super::Permit::acquire(&id).unwrap();
    let other = super::Permit::acquire(&other_id).unwrap();
    assert!(!first.cancelled.load(Ordering::Acquire));
    assert!(!other.cancelled.load(Ordering::Acquire));
    assert!(super::Permit::acquire(&id).is_err());
    assert!(Arc::ptr_eq(super::senders().lock().unwrap().get(&id).unwrap(), &first.cancelled));

    // Cancellation requests cleanup; only dropping the owning permit releases
    // admission. Never use global cancel_all in these concurrent unit tests.
    first.cancelled.store(true, Ordering::Release);
    assert!(super::Permit::acquire(&id).is_err());
    assert!(!other.cancelled.load(Ordering::Acquire));
    drop(first);
    assert!(!super::senders().lock().unwrap().contains_key(&id));
    assert!(super::Permit::acquire(&other_id).is_err(), "dropping one permit must not clear another");
    drop(other);
    assert!(!super::senders().lock().unwrap().contains_key(&other_id));
}

#[test]
fn broadcast_permit_drop_allows_a_fresh_attempt_with_an_independent_cancel_token() {
    let id = uuid::Uuid::new_v4().simple().to_string();
    let first = super::Permit::acquire(&id).unwrap();
    let retired_cancel = first.cancelled.clone();
    drop(first);
    let next = super::Permit::acquire(&id).unwrap();
    assert!(!Arc::ptr_eq(&retired_cancel, &next.cancelled));
    retired_cancel.store(true, Ordering::Release);
    assert!(!next.cancelled.load(Ordering::Acquire), "old cancellation must not affect a fresh attempt");
    assert!(super::Permit::acquire(&id).is_err());
    assert!(Arc::ptr_eq(super::senders().lock().unwrap().get(&id).unwrap(), &next.cancelled));
    drop(next);
    assert!(!super::senders().lock().unwrap().contains_key(&id));
}
