// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafAudioAsset = { path: string, start_frame: number, duration_frames: number, sample_rate: number, sample_count: number, peaks: Array<[number, number]>, };
