// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafClip = { start_frame: number, duration_frames: number, kind: string, master_id: string | null, source_id: string | null, source_start_sample: number | null, sample_rate: number | null, warnings: Array<string>, };
