// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A recognized word: sequence-relative 16 kHz samples, like its cue, and the
 * recognizer's confidence (0 to 1).
 */
export type AafCueWord = { text: string, start_sample: number, end_sample: number, confidence: number, };
