// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafCue = { id: string, 
/**
 * Sequence-relative position at 16 kHz. Never raw VAD-compacted token time.
 */
start_sample: number, end_sample: number, text: string, boundary_review: boolean, };
