// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafOwnershipLabel } from "./AafOwnershipLabel";

/**
 * "This cue is Rosa's" or "this cue is bleed from Dev's mic", said by the editor.
 */
export type AafCueOwnership = { track_id: string, cue_id: string, label: AafOwnershipLabel, heard_on?: string, };
