// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafCueWord } from "./AafCueWord";

export type AafCue = { id: string, 
/**
 * Sequence-relative position at 16 kHz. Never raw VAD-compacted token time.
 */
start_sample: number, end_sample: number, text: string, boundary_review: boolean, 
/**
 * Each word with the time the recognizer measured for it, when the
 * engine reports one (Parakeet does). Absent on documents written before
 * it was kept and on Whisper runs, whose words are still placed by
 * length (docs/TRANSCRIPT-ACCURACY-SPEC-2026-10-04.md, phase 1).
 */
words?: Array<AafCueWord>, 
/**
 * Why this cue may have been invented rather than heard (Whisper's
 * stock phrases and loops on silence). A label for the editor to check;
 * the cue is never removed (accuracy spec, phase 2).
 */
suspect?: string, };
