// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafDocumentSummary = { id: string, name: string, track_count: number, transcribed_tracks: number, source_path: string, };
