// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafDiagnosticEvent } from "./AafDiagnosticEvent";

export type AafDiagnostics = { events: Array<AafDiagnosticEvent>, active_jobs: Array<string>, persistence_error: string | null, context: string, };
