// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafDiagnosticEvent = { id: string, timestamp_ms: number, job_id: string, level: string, stage: string, message: string, 
/**
 * Only operation boundaries change activity. Subprocess stages do not.
 */
active: boolean | null, };
