// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafDocumentSummary = { id: string, 
/**
 * The sequence's name. Pages show `title` first (`documentName`).
 */
name: string, title?: string, track_count: number, transcribed_tracks: number, source_path: string, modified_ms?: number, };
