// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafManifest } from "./AafManifest";
import type { AafTrackLabel } from "./AafTrackLabel";
import type { AafTrackTranscript } from "./AafTrackTranscript";

export type AafDocument = { schema_version: number, id: string, source_path: string, source_size: number, source_modified_ms: number, manifest: AafManifest, labels: Array<AafTrackLabel>, transcripts: Array<AafTrackTranscript>, };
