// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafCueOwnership } from "./AafCueOwnership";
import type { AafManifest } from "./AafManifest";
import type { AafTrackLabel } from "./AafTrackLabel";
import type { AafTrackTranscript } from "./AafTrackTranscript";

export type AafDocument = { schema_version: number, id: string, source_path: string, source_size: number, source_modified_ms: number, manifest: AafManifest, labels: Array<AafTrackLabel>, transcripts: Array<AafTrackTranscript>, 
/**
 * None uses source metadata; Some("") explicitly clears an unknown date.
 */
shoot_date_override?: string, 
/**
 * The editor's own calls on who said a cue, which win over the bleed
 * resolver's (accuracy spec, phase 3). Keyed by cue, so a regenerated
 * transcript, whose cue ids are new, starts from the resolver again.
 */
ownership?: Array<AafCueOwnership>, };
