// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafImportedMarker } from "./AafImportedMarker";
import type { AafLane } from "./AafLane";
import type { AafPathMapping } from "./AafPathMapping";
import type { AafPictureTrack } from "./AafPictureTrack";
import type { AafSource } from "./AafSource";
import type { AafSourcePosition } from "./AafSourcePosition";

export type AafGraph = { sequence_id: string, sources: Array<AafSource>, lanes: Array<AafLane>, positions: Array<AafSourcePosition>, markers: Array<AafImportedMarker>, picture_tracks: Array<AafPictureTrack>, path_mappings: Array<AafPathMapping>, };
