// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafImportedMarker = { position: number, comment: string, described_slots: Array<number>, attributes: { [key in string]?: string }, };
