// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafLane = { track_id: string, parent_track_id: string | null, branch_id: string | null, group_name: string | null, availability: string, };
