// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafMarkerColor = "red" | "green" | "blue" | "cyan" | "yellow" | "magenta" | "white" | "black" | "purple" | "violet" | "pink" | "denim" | "forest" | "orange" | "gold" | "grey";
