// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafRate } from "./AafRate";
import type { AafTrack } from "./AafTrack";

export type AafManifest = { schema_version: number, name: string, source_fingerprint: string, edit_rate: AafRate, start_frame: number, duration_frames: number, timecode_fps: number, drop_frame: boolean, tracks: Array<AafTrack>, warnings: Array<string>, };
