// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafOwnershipCounts = { owner: number, bleed: number, overtalk: number, offmic: number, unsure: number, other: number, };
