// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafOwnershipCounts } from "./AafOwnershipCounts";
import type { AafWordOwnership } from "./AafWordOwnership";

export type AafOwnership = { document_id: string, 
/**
 * Tracks whose level was compared (their waveform exists).
 */
measured: Array<string>, 
/**
 * Transcribed tracks with no waveform yet: their words carry no label
 * until they are measured.
 */
missing: Array<string>, 
/**
 * Every word that is not plainly its mic owner's, and every word the
 * editor marked by hand. Words not listed are the owner's.
 */
words: Array<AafWordOwnership>, counts: AafOwnershipCounts, 
/**
 * What the answer was computed from; anything newer means compute again.
 */
stamp: string, 
/**
 * From the voice check: a possible mic swap, two voices too alike to tell
 * apart. Empty until the voices are checked.
 */
warnings: Array<string>, 
/**
 * How many mic owners' voices the voice check learned (0 until it runs).
 */
voices: number, };
