// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafPictureTrack = { slot_id: number, physical_track_number: number | null, name: string, component: string, };
