// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafPictureDescriptor } from "./AafPictureDescriptor";

export type AafPictureClip = { start_frame: number, duration_frames: number, kind: string, name: string | null, master_mob_id: string | null, file_mob_id: string | null, tape_name: string | null, source_start_frame: number | null, source_timecode_fps: number | null, source_drop_frame: boolean | null, group: boolean, effect: string | null, descriptor: AafPictureDescriptor | null, };
