// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafPictureDescriptor = { kind: string, sample_rate: string | null, stored_width: number | null, stored_height: number | null, frame_layout: string | null, compression: string | null, };
