// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafProgress = { job_id: string, track_id: string | null, phase: string, completed_frames: number, total_frames: number, };
