// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafResolvedSource = { path: string, fingerprint: string, stream_index: number, size: number, modified_ms: number, };
