// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafSourcePosition = { track_id: string, clip_index: number, numerator: number, denominator: number, };
