// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafWord } from "./AafWord";

/**
 * One track's analysis, in the 16 kHz sample units transcript cues use.
 */
export type AafSpeech = { track_id: string, 
/**
 * Median noise floor, dBFS: context for the editor, not used for decisions.
 */
floor_db: number, activity: Array<[number, number]>, reactions: Array<[number, number]>, words: Array<AafWord>, };
