// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafSourceAncestor = { mob_id: string, slot_id: number, start: number, edit_rate: string, locators: Array<string>, };
