// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafClip } from "./AafClip";

export type AafTrack = { id: string, name: string, clips: Array<AafClip>, warnings: Array<string>, };
