// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafGender } from "./AafGender";
import type { AafMarkerColor } from "./AafMarkerColor";

export type AafTrackLabel = { track_id: string, owner_name: string, cast_member_id: string | null, color: string | null, gender?: AafGender, marker_color?: AafMarkerColor, };
