// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafCue } from "./AafCue";
import type { AafEngine } from "./AafEngine";
import type { AafTimingIssue } from "./AafTimingIssue";
import type { AafTranscriptStatus } from "./AafTranscriptStatus";

export type AafTrackTranscript = { track_id: string, start_frame: number, duration_frames: number, engine: AafEngine, model_id: string, status: AafTranscriptStatus, sample_rate: number, cues: Array<AafCue>, timing_issues: Array<AafTimingIssue>, warnings: Array<string>, };
