// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Keep recognizer text with unusable timing, without inventing a seek position.
 */
export type AafTimingIssue = { id: string, text: string, reported_timing: string, chunk_start_frame: number, reason: string, };
