// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AafOwnershipLabel } from "./AafOwnershipLabel";

export type AafWordOwnership = { track_id: string, cue_id: string, 
/**
 * The word's position in its cue's text, split on spaces.
 */
index: number, label: AafOwnershipLabel, 
/**
 * For bleed: the track whose mic the word was really spoken into.
 */
heard_on?: string, 
/**
 * This mic's level over the word minus the loudest other mic's, against
 * each one's own floor.
 */
delta_db: number, 
/**
 * The editor said so; the resolver did not.
 */
manual: boolean, };
