// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AafWord = { cue_id: string, text: string, start_sample: number, end_sample: number, 
/**
 * The recognizer's confidence, 0 to 1, when it measured this word. Absent
 * for words placed by length.
 */
confidence?: number, };
