// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalysisRowCorrection = { revision: number, label: string | null, start_us: number | null, end_us: number | null, picture: string | null, dialogue: string | null, summary: string | null, };
