// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisEditRow } from "./AnalysisEditRow";
import type { AnalysisRowCorrection } from "./AnalysisRowCorrection";
import type { VideoAnalysisSource } from "./VideoAnalysisSource";

export type AnalysisEditDocument = { schema_version: number, revision: number, source: VideoAnalysisSource, fps: number, model: string | null, rows: Array<AnalysisEditRow>, corrections: { [key in string]?: AnalysisRowCorrection }, };
