// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminated union of every error a Tauri command can return.
 *
 * `#[serde(tag = "kind", content = "data")]` produces the canonical
 * TypeScript discriminated-union shape — `{ kind: "...", data: ... }`.
 * Variants without payload serialize as `{ kind: "..." }` (no `data`
 * key), which ts-rs reflects as `{ kind: "Cancelled" }` etc.
 */
export type AppError = { "kind": "Invalid", "data": string } | { "kind": "NotFound", "data": string } | { "kind": "Cancelled" } | { "kind": "SidecarMissing", "data": { name: string, } } | { "kind": "SidecarFailed", "data": { name: string, exit_code: number | null, tail: string, } } | { "kind": "YouTubeAuthRequired" } | { "kind": "Network", "data": string } | { "kind": "Io", "data": string } | { "kind": "Internal", "data": string };
