// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssistantReply = { 
/**
 * The model's final answer.
 */
text: string, 
/**
 * The tools it called, in order, for the status line and diagnostics.
 */
tools_used: Array<string>, };
