// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An avfoundation audio input the user can dictate from (for the mic chooser).
 */
export type AudioInputDevice = { 
/**
 * avfoundation enumeration index, as a string (e.g. "0").
 */
index: string, name: string, };
