// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The real camera + microphone TCC state, from AVFoundation. WKWebView's
 * JS Permissions API is unreliable for capture (it collapses to "prompt"/
 * throws, so the app can't otherwise tell "granted" from "denied" or from
 * "the OS grant hasn't taken effect until relaunch"). AVCaptureDevice's
 * authorizationStatus is the authoritative answer the UI needs.
 */
export type AvAuthStatus = { 
/**
 * "authorized" | "denied" | "notDetermined" | "restricted"
 */
camera: string, microphone: string, 
/**
 * Screen recording (r122): "authorized" | "notDetermined" only.
 * CGPreflightScreenCaptureAccess can't distinguish denied from
 * never-asked without prompting, so the UI must style non-authorized
 * as neutral not-yet, never as an error.
 */
screen: string, };
