// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheCategoryStats } from "./CacheCategoryStats";

/**
 * Cache stats for the Settings UI. `file_count`/`bytes_total` are the grand
 * totals across every category; the named fields break them down so the
 * user can see (and clear) each kind independently:
 *   - `downloads` / `audio` / `meta` — the persistent media cache (r112).
 *   - `thumbnails` — the keyed `saucebunny-thumb-*` files in the cache root.
 *   - `scratch` — every other `saucebunny-*` root file (job temps, playback
 *     prep copies, whisper wavs); the 24h startup sweep owns these.
 *
 * The `path` field surfaces the cache location in Settings so users
 * can find / reveal it. Settable-from-Settings is r40 work; r39 just
 * shows where files land.
 */
export type CacheStats = { file_count: number, bytes_total: number, path: string, downloads: CacheCategoryStats, audio: CacheCategoryStats, meta: CacheCategoryStats, thumbnails: CacheCategoryStats, scratch: CacheCategoryStats, };
