// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cache stats for the Settings UI — sum of all `saucebunny-*` files in
 * app_cache_dir(). Returns `(file_count, bytes_total, path)`.
 *
 * The `path` field surfaces the cache location in Settings so users
 * can find / reveal it. Settable-from-Settings is r40 work; r39 just
 * shows where files land.
 */
export type CacheStats = { file_count: number, bytes_total: number, path: string, };
