// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resolved direct-stream result + its validity window, persisted so a
 * re-open inside the window skips yt-dlp entirely.
 */
export type CachedStream = { video_url: string, 
/**
 * Raw DASH audio URL (the proxy merges it); None when muxed.
 */
audio_url: string | null, width: number | null, height: number | null, vcodec: string | null, acodec: string | null, 
/**
 * The preview height cap active at resolve time. A cached URL is only
 * reused when the caller's cap matches — the resolver picks a different
 * format per cap, and silently serving yesterday's 480p after the user
 * bumped quality to 1080p would be wrong.
 */
max_height: number | null, 
/**
 * Unix seconds when the resolve happened.
 */
resolved_at: number, 
/**
 * Unix seconds after which the signed URLs are invalid.
 */
expires_at: number, };
