// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-category slice of the cache, for the Settings breakdown.
 */
export type CacheCategoryStats = { file_count: number, bytes_total: number, };
