// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One cached web source, as the Library's web shelf needs it.
 *
 * Built from the warm-start metadata the resolver already writes, so this
 * adds no new bookkeeping — it reads what "download once, reuse forever"
 * has been recording all along.
 */
export type CachedWebItem = { url: string, title: string | null, thumbnail: string | null, uploader: string | null, duration_seconds: number | null, 
/**
 * Unix seconds when the page was last resolved.
 */
fetched_at: number, 
/**
 * The downloaded copy on disk, when there is one.
 */
path: string | null, size_bytes: number | null, };
