// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CaptureWindowThumbnail = { application: string, process: number, window: number, 
/**
 * Base64 JPEG only, without a data URL or persistent file path.
 */
thumb: string, };
