// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObsDisplayGeometry } from "./ObsDisplayGeometry";

export type CaptureDisplayThumbnail = { displayUuid: string, displayId: number, geometry: ObsDisplayGeometry, thumb: string, };
