// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudModel = { id: string, 
/**
 * The provider's display name, when it gives one (Anthropic does).
 */
name: string | null, 
/**
 * When the provider released it, in seconds since 1970, for newest first.
 */
created: number | null, 
/**
 * Whether it answers in text: OpenAI lists embedding, speech, image and
 * moderation models beside the chat ones, which a menu of chat models
 * should not offer first.
 */
chat: boolean, };
