// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiarizeProgressEvent = { job_id: string, 
/**
 * Raw JSON line as emitted by the sidecar — e.g.
 * `{"phase":"prepare","message":"Downloading…"}`. We forward
 * verbatim and let the frontend parse the shape; that keeps
 * the Rust side stable across sidecar schema bumps.
 */
line: string, };
