// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live interim transcript emitted while the user is still speaking (native
 * path only). The composer replaces its in-progress dictation text with this
 * on every event, so words appear in real time.
 */
export type DictatePartialEvent = { job_id: string, text: string, };
