// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DictateDoneEvent = { job_id: string, success: boolean, text: string | null, error: string | null, 
/**
 * Non-error advisory shown to the user (e.g. recording hit the time cap).
 */
note: string | null, };
