// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live mic level (0..1) emitted ~20×/s while recording, for the waveform UI.
 */
export type DictateLevelEvent = { job_id: string, level: number, };
