// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DirectStreamResult = { url: string, 
/**
 * DASH-split sources (Reddit, YouTube >360p, …) have no single muxed
 * progressive URL. When that's the case we resolve the best H.264 video
 * AND best AAC audio as separate URLs; the loopback proxy merges them on
 * the fly into fragmented MP4 (`/fmp4/v1/<b64video>?audio=<b64audio>`) so
 * the source STREAMS (with sound) instead of falling back to download.
 * `None` ⇒ `url` is already muxed (the common path).
 */
audio_url: string | null, width: number | null, height: number | null, vcodec: string | null, 
/**
 * Audio codec of the selected stream (e.g. "mp4a.40.2"). Lets the frontend
 * build an exact MSE MIME without probing the raw stream. None/NA ⇒ the
 * frontend assumes AAC (the resolver constrains the avc tiers to mp4a).
 */
acodec: string | null, };
