// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One capturable display. `index` is the avfoundation screen ordinal
 * (ffmpeg's "Capture screen N"), which follows CG's active-display order.
 */
export type DisplayInfo = { id: number, index: number, name: string, width: number, height: number, };
