// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DoneEvent = { job_id: string, success: boolean, code: number | null, path: string | null, error: string | null, };
