// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditSegment = { "kind": "source", id: string, source: string, in_frame: number, out_frame: number, 
/**
 * The lanes this clip plays on: a bite of one person, or an insert
 * with some source mics turned off. Every other record track is
 * filler for the clip, as it is in Avid when a track was not
 * selected. Absent: every patched lane plays (whole-sequence cuts,
 * and every clip made before clips named their tracks).
 */
tracks?: Array<string>, } | { "kind": "gap", id: string, frames: number, };
