// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditMarker } from "./EditMarker";
import type { EditMute } from "./EditMute";
import type { EditRate } from "./EditRate";
import type { EditSegment } from "./EditSegment";
import type { EditSource } from "./EditSource";
import type { EditTrack } from "./EditTrack";

export type EditDocument = { schema_version: number, title: string, edit_rate: EditRate, start_timecode_frames: number, sources: Array<EditSource>, tracks: Array<EditTrack>, segments: Array<EditSegment>, mutes: Array<EditMute>, markers: Array<EditMarker>, };
