// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditSegment = { "kind": "source", id: string, source: string, in_frame: number, out_frame: number, } | { "kind": "gap", id: string, frames: number, };
