// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditRate } from "./EditRate";

export type EditSummary = { id: string, title: string, created_at: number, updated_at: number, head: number, states: number, 
/**
 * What the String Outs list shows of it, read from its head: the
 * sequences it is cut from, how long it plays, and its bites (clips
 * that play a source, gaps not counted). Empty when the head cannot
 * be read, which the list survives.
 */
sources: Array<string>, duration_frames: number, bites: number, 
/**
 * Each bite's length in frames, in record order, for the list's strip
 * that draws the cut to scale. The first `STRIP_BITES` only: the strip
 * is a thumbnail, and a cut of thousands of bites must not ride along.
 */
bite_frames: Array<number>, edit_rate: EditRate | null, };
