// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditTrackKind } from "./EditTrackKind";

/**
 * One output track. `source_tracks` maps a source id to that source's AAF
 * track id, so a person's lane can draw on a different mic in each source.
 */
export type EditTrack = { id: string, name: string, kind: EditTrackKind, source_tracks: { [key in string]?: string }, };
