// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where segments come from: an AAF Audio document (one imported sequence).
 */
export type EditSource = { id: string, name: string, 
/**
 * The AAF Audio document id this source was imported as.
 */
document_id: string, };
