// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditDocument } from "./EditDocument";

/**
 * The head after a change of state, with the document it holds.
 */
export type EditHead = { state: number, label: string, document: EditDocument, 
/**
 * The label undo would take back, or null at the first state.
 */
undo: string | null, 
/**
 * The label redo would bring back, or null when nothing is ahead.
 */
redo: string | null, };
