// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one lane plays across a segment instead of the segment's clip: the
 * segment's length of `source` from `in_frame`, or with no source, nothing.
 */
export type EditOverride = { source: string | null, in_frame: number, };
