// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditState } from "./EditState";

/**
 * Every state of one edit plus the redo preference per state, which is all
 * the History panel needs to draw the done line, the steps ahead and the
 * branches (the drawing logic is shared with the prototype).
 */
export type EditHistory = { head: number, states: Array<EditState>, 
/**
 * Pairs of [parent, child]: the child redo returns to from that parent.
 */
next: Array<[number, number]>, };
