// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditOverride } from "./EditOverride";

export type EditSegment = { "kind": "source", id: string, source: string, in_frame: number, out_frame: number, 
/**
 * The lanes this clip plays on: a bite of one person, or an insert
 * with some source mics turned off. Every other record track is
 * filler for the clip, as it is in Avid when a track was not
 * selected. Absent: every patched lane plays (whole-sequence cuts,
 * and every clip made before clips named their tracks).
 */
tracks?: Array<string>, 
/**
 * Per lane, what it plays across this whole segment instead of the
 * clip: an Overwrite or a Lift made with only that track selected.
 */
overrides?: { [key in string]?: EditOverride }, 
/**
 * Per lane, the record track (1 for A1) it sits on in this segment.
 * A record track is a layer, as in Avid, not a person: A1 can hold
 * one person's mic here and someone else's in the next clip. A lane
 * this does not name sits on the track it was patched to, which is
 * all a string out from before layers knew.
 */
layers?: { [key in string]?: number }, 
/**
 * Lanes with an edit of their own where this segment starts though
 * their material runs straight on: a through edit made by Add Edit or
 * the blade on their track.
 */
cuts?: Array<string>, } | { "kind": "gap", id: string, frames: number, };
