// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditTrackKind } from "./EditTrackKind";

/**
 * One output track. `source_tracks` maps a source id to that source's AAF
 * track id, so a person's lane can draw on a different mic in each source.
 */
export type EditTrack = { id: string, name: string, kind: EditTrackKind, source_tracks: { [key in string]?: string }, 
/**
 * Whether this person is patched to a record track. `false`: listed, so
 * their words can be found and cut in, but on no track, so they neither
 * play nor export. `true`: patched, on the next track down (tracks are
 * numbered top-down in the order they appear here). Absent: patched, as
 * every person was in string outs made before patching, so those open
 * exactly as they were saved. A new string out patches nobody until
 * someone's words are cut in, the way an Avid sequence starts with no
 * tracks. `featured != Some(false)` is the on-track rule on both sides
 * of the invoke. (The name predates patching: it first meant only a
 * group angle given a track, and renaming it would orphan saved edits.)
 */
featured?: boolean, };
