// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The part of the writer's answer the app shows. Unknown fields are ignored,
 * so the writer can report more without breaking the invoke.
 */
export type EditExportResult = { output: string, markers_output: string | null, name: string, duration_frames: number, segments: number, markers: number, copied_mobs: number, warnings: Array<string>, };
