// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditMarker = { id: string, 
/**
 * Program frame.
 */
frame: number, track: string | null, name: string, comment: string, color: string, };
