// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditExportResult } from "./EditExportResult";

/**
 * One edit of a batch export: what was written, or why that edit was not.
 * The other edits of the batch are written either way.
 */
export type EditExportOutcome = { edit_id: string, result: EditExportResult | null, error: string | null, };
