// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tag: a label plus one of Finder's eight colour slots (0 = no colour).
 */
export type FinderTag = { name: string, 
/**
 * 0 = none, 1-7 = grey, green, purple, blue, yellow, red, orange.
 */
color: number, };
