// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One grabbed frame, as the Library's Frames shelf needs it.
 */
export type FrameItem = { 
/**
 * Absolute path - a real file, so every path verb (reveal, Quick Look,
 * drag) works on it without translation.
 */
path: string, 
/**
 * Filename including extension.
 */
name: string, 
/**
 * The source stem the shelf groups on, derived from the filename.
 */
source: string, 
/**
 * The timecode tail, when the name carries one ("00012304").
 */
timecode: string | null, 
/**
 * Unix seconds, file mtime. `ts(type)` because ts-rs maps u64 to
 * bigint, and JSON never produces one - the same annotation
 * CachedWebItem carries for the same reason.
 */
created_at: number, size_bytes: number, };
