// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a grant looks like to the frontend. Same as `ReviewGrant` minus the
 * hash, which the webview has no use for and should not hold.
 */
export type GrantSummary = { id: string, label: string, createdAt: bigint, lastSeenAt: bigint | null, revoked: boolean, };
