// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The newest published release, as the frontend needs it.
 */
export type LatestRelease = { 
/**
 * Tag as published, e.g. "v0.2.0". The frontend parses the semver.
 */
version: string, 
/**
 * Human page to send the user to.
 */
url: string, 
/**
 * Release notes body, trimmed. May be empty.
 */
notes: string, };
