// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Media kind of one library item, decided purely by file extension.
 * Serializes lowercase, so the TS side sees `"video" | "audio"`.
 */
export type LibraryItemKind = "video" | "audio";
