// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryItemKind } from "./LibraryItemKind";

/**
 * One playable file found by the scan. Duration/thumbnail are deliberately
 * absent — fetched lazily by the frontend (see module docs).
 */
export type LibraryItem = { name: string, path: string, size_bytes: number, 
/**
 * Last-modified time as Unix milliseconds; 0 when the FS won't say.
 */
modified_ms: number, kind: LibraryItemKind, };
