// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryItem } from "./LibraryItem";

/**
 * One folder node of the scanned tree, root included.
 */
export type LibraryFolder = { name: string, path: string, folders: Array<LibraryFolder>, items: Array<LibraryItem>, };
