// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryReferenceStatus = { path: string, 
/**
 * Unknown on access errors; a denied drive is not a missing file.
 */
exists: boolean | null, };
