// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LlmModel = { id: string, name: string, size_bytes: number, ctx: number, recommended: boolean, blurb: string, downloaded: boolean, };
