// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LlmServerInfo = { 
/**
 * e.g. http://127.0.0.1:51234 — the frontend POSTs /v1/chat/completions here.
 */
base_url: string, 
/**
 * Per-session bearer token; required on every request (Authorization header).
 */
api_key: string, model_id: string, ctx: number, };
