// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalFileMeta = { path: string, filename: string, size_bytes: number, duration: number | null, width: number | null, height: number | null, fps: number | null, vcodec: string | null, acodec: string | null, has_video: boolean, has_audio: boolean, };
