// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpSetup = { 
/**
 * This app's executable, which serves MCP with `--mcp`.
 */
command: string, 
/**
 * The line to paste into a terminal for Claude Code.
 */
claude_code: string, 
/**
 * The entry for `claude_desktop_config.json`, for anyone who adds servers by hand.
 */
desktop_config: string, };
