// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaState } from "./MediaState";

export type MediaAvailability = { path: string, state: MediaState, 
/**
 * The drive's name for a path under /Volumes ("NEXIS"), to say which one to connect.
 */
volume: string | null, 
/**
 * Whether an online path is a folder.
 */
folder: boolean, };
