// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaInfoVideo = { codec: string, 
/**
 * Container fourcc, e.g. `apch` = ProRes 422 HQ.
 */
codec_tag: string | null, profile: string | null, width: number, height: number, pix_fmt: string | null, bit_depth: number | null, 
/**
 * ffprobe field_order: "progressive", "tt", "bb", "tb", "bt", or unknown.
 */
field_order: string | null, fps: number | null, 
/**
 * The exact rational, e.g. "30000/1001".
 */
fps_exact: string | null, 
/**
 * True when avg_frame_rate ≠ r_frame_rate (variable frame rate).
 */
vfr: boolean, bitrate_bps: number | null, color_space: string | null, color_transfer: string | null, color_primaries: string | null, nb_frames: number | null, 
/**
 * Every sampled packet is a keyframe (I-frame-only codec).
 */
all_intra: boolean | null, keyframe_ratio: number | null, 
/**
 * Bitrate varies across ~1s windows (sampled) → VBR.
 */
vbr: boolean | null, 
/**
 * Coefficient of variation of per-window byte totals (0 = perfectly constant).
 */
bitrate_cv: number | null, };
