// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaInfoAudio } from "./MediaInfoAudio";
import type { MediaInfoVideo } from "./MediaInfoVideo";

export type MediaInfo = { container: string, duration_s: number | null, size_bytes: number, overall_bitrate_bps: number | null, 
/**
 * Embedded start timecode (QuickTime tmcd / format tag), if any.
 */
timecode: string | null, video: MediaInfoVideo | null, audio: MediaInfoAudio | null, };
