// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaInfoAudio = { codec: string, channels: number, channel_layout: string | null, sample_rate: number | null, sample_fmt: string | null, bitrate_bps: number | null, vbr: boolean | null, bitrate_cv: number | null, };
