// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Metadata = { title: string, duration: number | null, thumbnail: string | null, uploader: string | null, upload_date: string | null, view_count: number | null, webpage_url: string, width: number | null, height: number | null, fps: number | null, vcodec: string | null, acodec: string | null, ext: string | null, has_subs: boolean, };
