// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceChapter } from "./SourceChapter";

export type Metadata = { title: string, duration: number | null, thumbnail: string | null, uploader: string | null, upload_date: string | null, view_count: number | null, webpage_url: string, width: number | null, height: number | null, fps: number | null, vcodec: string | null, acodec: string | null, ext: string | null, has_subs: boolean, 
/**
 * The creator's OWN chapters, when the site publishes them.
 *
 * This app used to infer chapters from the transcript with a local LLM -
 * slow, and a guess - while yt-dlp had the real ones sitting in the same
 * `--dump-json` probe we already run. Real beats inferred on both speed
 * and accuracy; the LLM stays as the fallback for sources that publish
 * none.
 */
chapters: Array<SourceChapter>, 
/**
 * The video description. Free context for the AI summary: creators put
 * guest names, timestamps and links here, and none of it was reaching us.
 * Capped, because a description can be pathologically long and it rides
 * in a struct that gets cached to disk and passed across the IPC boundary.
 */
description: string | null, };
