// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelProgressEvent = { job_id: string, model_id: string, percent: number, bytes_done: number, bytes_total: number, };
