// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NdiRuntimeState } from "./NdiRuntimeState";
import type { NdiSource } from "./NdiSource";

export type NdiDiscoveryResult = { bridgeCompiled: boolean, runtime: NdiRuntimeState, runtimeVersion: string | null, sources: Array<NdiSource>, error: string | null, };
