// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NdiRuntimeState } from "./NdiRuntimeState";

export type NdiPreflightResult = { bridgeCompiled: boolean, runtime: NdiRuntimeState, runtimeVersion: string | null, runtimeOrigin: 'bundled' | 'developer' | 'missing', premiereInstalled: boolean, premiereVersion: string | null, pluginInstalled: boolean, error: string | null, };
