// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NdiRoomProgram } from "./NdiRoomProgram";

export type NdiRoomState = { generation: number, presenterEpoch: number, presenting: boolean, publishedId: string | null, publicationRevision: number | null, source: NdiRoomProgram | null, };
