// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NdiPublicationState } from "./NdiPublicationState";

export type NdiRoomProgram = { id: string, name: string, reviewKey: string, state: NdiPublicationState, };
