// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NdiRoomState } from "./NdiRoomState";
import type { NdiStatusResult } from "./NdiStatusResult";

export type NdiSessionsResult = { programs: Array<NdiStatusResult>, room: NdiRoomState | null, };
