// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NdiStarted } from "./NdiStarted";
import type { NdiTelemetry } from "./NdiTelemetry";

export type NdiStatusResult = { program: NdiStarted | null, telemetry: NdiTelemetry, encodedReady: boolean, roomGeneration: number | null, };
