// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Raw time fields use decimal strings: NDI's signed 64-bit clock values do
 * not fit exactly in a JavaScript number. Equal fields are not frame proof.
 */
export type NdiTimingSample = { probeId: string, sampleSequence: number, outputTick: string | null, outputTimescale: number, outputAccepted: boolean, inputValid: boolean, inputWidth: number, inputHeight: number, inputRateN: number, inputRateD: number, ndiTimecode: string | null, ndiTimestamp: string | null, metadata: string | null, metadataTruncated: boolean, metadataInvalidUtf8: boolean, sameTimingAsPreviousCapture: boolean, receivedFrames: string, ndiDroppedFrames: string, encoderDroppedFrames: string, lastInputAgeMs: number, stale: boolean, };
