// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NdiPhase } from "./NdiPhase";

export type NdiTelemetry = { sourceId: string, phase: NdiPhase, error: string | null, inputWidth: number, inputHeight: number, outputFps: number, inputFps: number | null, connectionCount: number | null, receivedFrames: number, ndiDroppedFrames: number, encoderDroppedFrames: number, encoderDroppedAudioSamples: number, leftPeak: number, rightPeak: number, lastInputAgeMs: number, encodedBitrateKbps: number | null, };
