// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NdiTimingProbePhase } from "./NdiTimingProbePhase";
import type { NdiTimingSample } from "./NdiTimingSample";

export type NdiTimingProbeResult = { sourceId: string, probeId: string, phase: NdiTimingProbePhase, remainingMs: number, capacity: number, overwrittenSamples: number, rejectedSamples: number, timingVerified: boolean, samples: Array<NdiTimingSample>, };
