// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObsAudioSpectrum } from "./ObsAudioSpectrum";

export type ObsAudioAcceptanceReport = { systemAudio: boolean, verdict: string, capture: ObsAudioSpectrum, reference: ObsAudioSpectrum, };
