// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObsAudioAcceptanceReport } from "./ObsAudioAcceptanceReport";

export type ObsAudioAcceptanceStatus = { attempt: string, phase: string, error: string | null, report: ObsAudioAcceptanceReport | null, };
