// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObsAudioChannelMetrics } from "./ObsAudioChannelMetrics";

export type ObsAudioSpectrum = { frames: number, sampleRate: number,
/**
 * Stereo channel order: left, right.
 */
channels: Array<ObsAudioChannelMetrics>, };
