// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ObsAudioChannelMetrics = { rms: number, longestQuietMs: number,
/**
 * Tone order: 440, 660, 880, 1320 Hz. Extrema span every 100 ms window.
 */
minimumTone: [number, number, number, number], maximumTone: [number, number, number, number], };
