// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObsBroadcastPhase } from "./ObsBroadcastPhase";

export type ObsBroadcastStatus = { sourceId: string, 
/**
 * Renderer intent counter only; never an OBS raw-output generation.
 */
attempt: number, phase: ObsBroadcastPhase, error: string | null, 
/**
 * Cleanup proof is independent of failure. Omitted when no authoritative
 * proof is available, including synchronous startup admission failures.
 */
cleanupConfirmed?: boolean, };
