// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exact observed logical bounds and backing-pixel dimensions. A moved,
 * resized, rotated or reconfigured target must be selected again.
 */
export type ObsDisplayGeometry = { x: number, y: number, width: number, height: number, pixelWidth: number, pixelHeight: number, };
