// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObsCrop } from "./ObsCrop";
import type { ObsDisplayGeometry } from "./ObsDisplayGeometry";
import type { ObsDisplayKind } from "./ObsDisplayKind";

export type ObsDisplaySelection = { kind: ObsDisplayKind, displayUuid: string, displayId: number, geometry: ObsDisplayGeometry, crop: ObsCrop, audio: boolean, };
