// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NdiStarted } from "./NdiStarted";
import type { ObsSelection } from "./ObsSelection";

export type ObsStarted = { program: NdiStarted, selection: ObsSelection, };
