// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObsDisplaySelection } from "./ObsDisplaySelection";
import type { ObsWindowSelection } from "./ObsWindowSelection";

export type ObsSelection = ObsWindowSelection | ObsDisplaySelection;
