// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ObsWindowChoice = { applicationName: string, id: number, pid: number, app: string, title: string, width: number, height: number, };
