// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObsCrop } from "./ObsCrop";

export type ObsWindowSelection = { application: string, process: number, window: number, crop: ObsCrop, audio?: boolean, };
