// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One session member: a session-scoped id (m0 = host, m1, m2, ... minted
 * at Hello) + display name. Ids are the roster key - names are display-only
 * and can collide. An id is RECLAIMED when the same install rejoins (r124),
 * so a reconnect updates a slot instead of adding a duplicate row.
 */
export type PeerInfo = { id: string, name: string, 
/**
 * Bumped every time this id is claimed or reclaimed. The RTC mesh keys
 * its peer connections on (id, epoch): a bump means "same person, new
 * connection", so the stale PeerConnection is torn down and rebuilt
 * instead of sitting on "Connecting" forever.
 */
epoch: number, };
