// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One session member: a session-scoped id (m0 = host, m1, m2, ... minted
 * at Hello, never reused) + display name. Ids are the roster key - names
 * are display-only and can collide.
 */
export type PeerInfo = { id: string, name: string, };
