// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A row the page reports about itself: String Outs' calls that waited, failed
 * or ran long, its stalls and its uncaught errors. Written into the same
 * journal as the backend's own, so the Pipeline is one timeline.
 */
export type PipelineRow = { job_id: string, level: string, stage: string, message: string, };
