// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PipelineHealth = { 
/**
 * The app process's resident memory, when macOS reports it.
 */
resident_bytes: number | null, uptime_seconds: number, 
/**
 * Job ids with a sidecar process registered right now.
 */
running_jobs: Array<string>, 
/**
 * How long the main thread has gone without answering the watchdog; 0 while it answers.
 */
main_thread_wait_ms: number, 
/**
 * Mounted volumes other than the startup disk: where, what kind, local or network.
 */
volumes: Array<string>, 
/**
 * The newest hang sample's file and its main-thread part, if one was recorded.
 */
latest_hang: string | null, 
/**
 * The co-review session: off, hosting or joined. Its UDP sockets and relay
 * connection exist only while one is open (session.rs), so this says
 * whose they are when Activity Monitor shows them.
 */
co_review: string, };
