// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PremiereMarkerState = "needs_confirmation" | "dispatching" | "uncertain" | "added" | "removed_in_premiere";
