// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PremiereBinding = { bindingId: string, projectId: string, sequenceId: string, projectName: string, sequenceName: string, timebaseTicks: string, displayFormat: string, zeroPointTicks: string, };
