// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PremiereMarkerRequest } from "./PremiereMarkerRequest";
import type { PremiereMarkerState } from "./PremiereMarkerState";

export type PremiereMarkerRecord = { id: string, request: PremiereMarkerRequest, status: PremiereMarkerState, sequenceTicks: string | null, markerGuid: string | null, error: string | null, };
