// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PremiereBinding } from "./PremiereBinding";

export type PremiereBridgeSnapshot = { phase: 'off' | 'pairing' | 'connected', binding: PremiereBinding | null, syncEnabled: boolean, automaticPlacement: false, pendingCount: number, otherBindingPendingCount: number, ledgerRevision: number, error: string | null, };
