// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PremiereBinding } from "./PremiereBinding";

export type PremiereAnchor = { binding: PremiereBinding, capturedAt: number, sourceId: string, streamId?: string, frameId?: string, mediaSeconds?: number, sequenceTicks?: string, verification: 'unverified' | 'verified', reason?: string, };
