// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PremiereAnchor } from "./PremiereAnchor";

export type PremiereMarkerRequest = { reviewKey: string, versionId: string, commentId: string, sessionId: string | null, author: string, body: string, anchor: PremiereAnchor, };
