// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgramCaptureKind } from "./ProgramCaptureKind";

export type ProgramCapturePreflight = { available: boolean, error: string | null, 
/**
 * The kinds this build can capture; the dialog shows only these tabs.
 */
kinds: Array<ProgramCaptureKind>, 
/**
 * System and application audio need macOS 14.2 (a Core Audio process tap).
 */
systemAudio: boolean, };
