// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A still of a pick, to draw a region on, and the size a capture of it encodes at.
 */
export type ProgramCaptureSnapshot = { image: string, width: number, height: number, };
