// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgramCaptureKind } from "./ProgramCaptureKind";

export type ProgramCaptureChoice = { choice: string, kind: ProgramCaptureKind, label: string, width: number, height: number, };
