// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObsCrop } from "./ObsCrop";
import type { ProgramCaptureKind } from "./ProgramCaptureKind";

/**
 * What the Preview captures: a pick the helper holds under `choice`.
 */
export type ProgramCaptureSelection = { choice: string, kind: ProgramCaptureKind, 
/**
 * Shown in the dialog and the room: the display's name, or "App · Window title".
 */
label: string, audio: boolean, 
/**
 * Only these applications' sound (bundle identifiers), so nobody in a call
 * hears themselves back. Absent: a window's own app, or every app but
 * Sauce Bunny for a screen or region.
 */
audioApps?: Array<string>, 
/**
 * Region only: the part of the picked display, each edge a fraction of it.
 */
region?: ObsCrop, };
