// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgramCaptureChoice } from "./ProgramCaptureChoice";

export type ProgramCaptureChooseResult = { "outcome": "chosen", choice: ProgramCaptureChoice, } | { "outcome": "cancelled" };
