// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An application whose sound can be chosen for a capture.
 */
export type ProgramCaptureApp = { bundle: string, name: string, };
