// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgramCaptureKind } from "./ProgramCaptureKind";

export type ProgramCapturePreflight = { available: boolean, error: string | null, 
/**
 * The kinds this build can capture; the dialog shows only these tabs.
 */
kinds: Array<ProgramCaptureKind>, 
/**
 * System audio needs macOS 14.2 (a Core Audio process tap).
 */
systemAudio: boolean, 
/**
 * A window's own application audio also needs macOS 15.2, the first to name a picked window's app.
 */
applicationAudio: boolean, };
