// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordingHandle = { id: string, 
/**
 * Wall clock when it started, so the UI can run its own elapsed timer
 * rather than being told the elapsed time twice a second.
 */
startedMs: bigint, 
/**
 * Pixel size actually being written, straight off the engine's meta line.
 */
width: number, height: number, 
/**
 * True when system audio is being captured. Video-only is a degrade, not
 * a failure: a FIFO that cannot be made must not lose the picture too.
 */
audio: boolean, };
