// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordingResult = { 
/**
 * The finished file. A path, and deliberately NOT something that goes on
 * the wire - see the Recording session message, which carries no path.
 */
path: string, bytes: bigint, seconds: bigint, };
