// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The high-resolution representation is intentionally separate from the
 * completed review copy. The review copy is stable, local and optimized for
 * random frame access; this source may expire and is used only for parked or
 * playing presentation.
 */
export type ResolvedPresentationSource = { "kind": "hls", manifestUrl: string, expiresAt: number, width: number | null, height: number | null, videoCodec: string | null, audioCodec: string | null, } | { "kind": "progressive", videoUrl: string, expiresAt: number, width: number | null, height: number | null, videoCodec: string | null, audioCodec: string | null, } | { "kind": "split", videoUrl: string, audioUrl: string, expiresAt: number, width: number | null, height: number | null, videoCodec: string | null, audioCodec: string | null, };
