// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerInfo } from "./PeerInfo";

export type SessionState = { role: string, code: string | null, peers: Array<PeerInfo>, selfId: string | null, title: string | null, error: string | null, 
/**
 * Member id currently allowed to drive source + transport. "" while off.
 * Distinct from the network host, which never moves.
 */
presenter: string, 
/**
 * Increments on every floor grant. Receivers use it to order transport
 * across a handover (see HostShared::presenter_epoch).
 */
presenterEpoch: number, };
