// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerInfo } from "./PeerInfo";

export type SessionMsg = { "kind": "hello", name: string, } | { "kind": "welcome", you: string, } | { "kind": "peerList", peers: Array<PeerInfo>, } | { "kind": "rtc", from: string, to: string, payload: string, } | { "kind": "loadSource", url: string, } | { "kind": "transport", playing: boolean, position: number, rate: number, atMs: number, seq: number, } | { "kind": "reviewOp", op: string, } | { "kind": "reviewDoc", doc: string, } | { "kind": "presence", name: string, position: number, } | { "kind": "sharing", from: string, on: boolean, };
