// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerInfo } from "./PeerInfo";

export type SessionState = { role: string, code: string | null, peers: Array<PeerInfo>, selfId: string | null, title: string | null, error: string | null, };
