// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerInfo } from "./PeerInfo";

export type SessionMsg = { "kind": "hello", name: string, install: string, } | { "kind": "welcome", you: string, title: string | null, } | { "kind": "peerList", peers: Array<PeerInfo>, } | { "kind": "rtc", from: string, to: string, payload: string, } | { "kind": "loadSource", from: string, sourceKind: string, url: string | null, fingerprint: string | null, title: string | null, duration: number | null, reviewKey: string, } | { "kind": "sourceStatus", from: string, state: string, detail: string | null, } | { "kind": "presenter", member: string, epoch: number, } | { "kind": "bye" } | { "kind": "transport", playing: boolean, position: number, rate: number, atMs: number, seq: number, 
/**
 * Host-stamped sender id + the presenter epoch it was sent under, so
 * lines from a superseded presenter can be ordered and discarded.
 */
from: string, epoch: number, } | { "kind": "reviewOp", op: string, } | { "kind": "reviewDoc", doc: string, } | { "kind": "presence", name: string, position: number, } | { "kind": "sharing", from: string, on: boolean, } | { "kind": "reaction", from: string, emote: string, on: boolean, };
