// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionMsg = { "kind": "hello", name: string, } | { "kind": "peerList", peers: Array<string>, } | { "kind": "loadSource", url: string, } | { "kind": "transport", playing: boolean, position: number, rate: number, atMs: number, seq: number, };
