// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A shareable display or window for the picker, with an optional base64
 * JPEG thumbnail (SCScreenshotManager via the capture sidecar).
 */
export type ShareDisplay = { id: number, width: number, height: number, label: string, thumb: string | null, };
