// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShareDisplay } from "./ShareDisplay";
import type { ShareWindow } from "./ShareWindow";

export type ShareSources = { displays: Array<ShareDisplay>, windows: Array<ShareWindow>, 
/**
 * False when the capture sidecar is missing - windows/portion/audio
 * unavailable, displays fall back to the ffmpeg path.
 */
capture_engine: boolean, };
