// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to share: a display, a window, or a portion of a display (the
 * Zoom Advanced-tab shape). Windows and system audio need the
 * saucebunny-capture sidecar (ScreenCaptureKit); the proxy falls back to
 * ffmpeg's display capture when it's absent.
 */
export type ShareSourceArg = { 
/**
 * "display" | "window"
 */
kind: string, 
/**
 * CGDirectDisplayID for displays, CGWindowID for windows.
 */
id: number, 
/**
 * Portion of a display, in display points: "x,y,w,h".
 */
crop: string | null, 
/**
 * Share system audio too (ScreenCaptureKit path only).
 */
audio: boolean, };
