// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SniffResult = { 
/**
 * Every media-looking URL the page fetched, in the order observed. The
 * frontend ranks them (see `lib/media-sniff.ts`) because the CHOICE
 * between a canonical and a signed URL is a product decision, not a
 * transport one.
 */
urls: Array<string>, 
/**
 * The page's own title, used to name the import when we have nothing else.
 */
title: string | null, };
