// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One chapter as the site published it.
 */
export type SourceChapter = { 
/**
 * Start time in seconds. Named to match the frontend's `Chapter.time`.
 */
time: number, title: string, };
