// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinderTag } from "./FinderTag";

/**
 * A file and whatever tags it carries.
 */
export type TaggedPath = { path: string, tags: Array<FinderTag>, };
