// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One transcript's text, for the cross-transcript search index.
 */
export type TranscriptText = { path: string, text: string, 
/**
 * Mtime in ms, so the frontend can drop a re-transcribed file from its
 * in-memory index without stat-ing every file itself.
 */
modified_ms: number, };
