// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A complete Whisper SRT exists, while speaker detection may still be running.
 */
export type TranscriptPreviewEvent = { job_id: string, path: string, };
