// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One transcript file found under the Transcripts library.
 */
export type TranscriptFile = { 
/**
 * Filename stem, no extension — the display title.
 */
name: string, 
/**
 * Absolute path to the .srt / .vtt on disk.
 */
path: string, 
/**
 * Immediate parent folder name (e.g. "2026-07"); "" when directly in root.
 */
folder: string, size_bytes: number, modified_ms: number, 
/**
 * A co-located `<stem>.diarization.json` sidecar exists (r132) → the
 * transcript carries speaker turns.
 */
has_diarization: boolean, 
/**
 * A co-located `<stem>.analysis.json` sidecar exists → the transcript has
 * a saved AI analysis to reuse.
 */
has_analysis: boolean, 
/**
 * "srt" | "vtt".
 */
format: string, };
