// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptScanHit } from "./TranscriptScanHit";

export type TranscriptScanResult = { hits: Array<TranscriptScanHit>, rows: number, chunks: number, failed: number, };
