// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stage marker emitted at well-known transitions in the transcript
 * pipeline. The Sidebar reads these to label the progress bar
 * ("Whisper" → "Diarize" → "Merge") instead of scraping log strings.
 *
 * Known phases (extensible):
 *   "whisper"          — whisper-cli is running
 *   "diarize-prepare"  — FluidAudio loading / downloading Core ML models
 *   "diarize-process"  — diarization is running on the audio
 *   "diarize-merge"    — stitching speaker labels into the SRT
 */
export type TranscriptPhaseEvent = { job_id: string, phase: string, };
