// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A line the scan found, by address, and why.
 */
export type TranscriptScanHit = { line: string, why: string, };
