// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoAnalysisSource = { path: string, sha256: string, duration_us: number, origin_us: number, };
