// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoSource = { key: string, path: string, duration: number, model: string, complete: number, available: boolean, segments: number, };
