// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoHit = { id: number, source_key: string, path: string, start: number, end: number, frames: Array<number>, score: number, };
