// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoProxyTimeSpan = { analysis_start_us: number, analysis_end_us: number, source_start_us: number, source_end_us: number, };
