// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoShotAnalysis } from "./VideoShotAnalysis";

export type VideoProgress = { job_id: string, phase: string, completed: number, total: number,
/**
 * One complete, source-bound description. Never token fragments.
 */
shot_analysis?: VideoShotAnalysis, };
