// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoAnalysisSource } from "./VideoAnalysisSource";
import type { VideoAudioStatus } from "./VideoAudioStatus";
import type { VideoMusicWindow } from "./VideoMusicWindow";

export type VideoMusicAnalysis = { analysis_id: string, source: VideoAnalysisSource, audio_track_index: number, classifier: string, os: string, preprocessing_version: string, status: VideoAudioStatus, labels: Array<string>, windows: Array<VideoMusicWindow>, };
