// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Boundaries are supplied by the scene detector in source-relative time.
 * The video model may describe them, never generate or reposition them.
 */
export type VideoShot = { id: number, start_us: number, end_us: number, transcript: string, };
