// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoAnalysisSource } from "./VideoAnalysisSource";
import type { VideoProxyTimeSpan } from "./VideoProxyTimeSpan";

export type VideoSceneProxy = { schema_version: string, proxy_version: string, time_map_version: string, source: VideoAnalysisSource, path: string, sha256: string, frame_count: number, pts_sha256: string, time_map: Array<VideoProxyTimeSpan>, };
