// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoModel = { id: string, name: string, role: string, bytes: number, ready: boolean, };
