// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoAnalysisSource } from "./VideoAnalysisSource";
import type { VideoAudioStatus } from "./VideoAudioStatus";
import type { VideoAudioWindow } from "./VideoAudioWindow";

/**
 * Raw actual-audio evidence, not a calibrated genre or music-presence verdict.
 * Missing ranges and insufficient-context tails remain visibly unclassified.
 */
export type VideoAudioAnalysis = { analysis_id: string, source: VideoAnalysisSource, audio_track_index: number, classifier: string, os: string, preprocessing_version: string, status: VideoAudioStatus, windows: Array<VideoAudioWindow>, };
