// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoAnalysisSource } from "./VideoAnalysisSource";
import type { VideoAnswer } from "./VideoAnswer";
import type { VideoHit } from "./VideoHit";
import type { VideoModel } from "./VideoModel";
import type { VideoSceneProxy } from "./VideoSceneProxy";
import type { VideoShotAnalysis } from "./VideoShotAnalysis";
import type { VideoSource } from "./VideoSource";

export type VideoResponse = { models: Array<VideoModel>, sources: Array<VideoSource>, hits: Array<VideoHit>, answers: Array<VideoAnswer>, analysis_source?: VideoAnalysisSource, shot_analysis?: VideoShotAnalysis, scene_proxy?: VideoSceneProxy, };
