// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoAudioScore } from "./VideoAudioScore";
import type { VideoAudioWindowStatus } from "./VideoAudioWindowStatus";

export type VideoAudioWindow = { start_us: number, end_us: number, rms: number, peak: number, status: VideoAudioWindowStatus, classifications: Array<VideoAudioScore>, };
