// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoShotAnswer = { id: number, start_us: number, end_us: number, frame_pts_us: number[], transcript: string, text: string, };
