// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoAudioWindowStatus } from "./VideoAudioWindowStatus";

/**
 * Shared vocabulary avoids repeating 527 labels for every ten-second window.
 */
export type VideoMusicWindow = { start_us: number, end_us: number, rms: number, peak: number, status: VideoAudioWindowStatus, scores: Array<number>, };
