// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoRequest = { "operation": "models", } | { "operation": "download", model_id: string, } | { "operation": "delete-model", model_id: string, } | { "operation": "sources", } | { "operation": "forget", source_key: string, } | { "operation": "index", paths: Array<string>, } | { "operation": "search", query: string, scope: Array<string>, rerank: boolean, } | { "operation": "reason", query: string, segments: Array<number>, transcripts: { [key in string]?: string }, };
