// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoAnalysisSource } from "./VideoAnalysisSource";
import type { VideoShotAnswer } from "./VideoShotAnswer";

export type VideoShotAnalysis = { analysis_id: string, source: VideoAnalysisSource, model_id: string, model_revision: string, sampling_version: string, audio_analyzed: boolean, shots: Array<VideoShotAnswer>, };
