// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CachedStream } from "./CachedStream";
import type { Metadata } from "./Metadata";

/**
 * Everything the frontend needs to decide the re-open path, in one call.
 */
export type WarmStart = { 
/**
 * Cached parsed metadata — hydrate the UI from this immediately.
 */
metadata: Metadata | null, 
/**
 * True when the metadata is missing or >24h old: revalidate in the
 * background (the UI still hydrates from the cached copy first).
 */
metadata_stale: boolean, 
/**
 * A still-valid resolved stream (expiry margin + height cap already
 * checked): hand it straight to the proxy/MSE path, skip extraction.
 */
stream: CachedStream | null, 
/**
 * A complete downloaded copy on disk: boot LocalMediaPlayer from this
 * and skip resolve/proxy altogether (the strongest fast path).
 */
cached_copy: string | null, };
