// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WhisperModel = { id: string, name: string, size_bytes: number, url: string, downloaded: boolean, path: string | null, };
