// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reported back to the YouTube Settings tab: the resolved yt-dlp version string
 * and whether it's the user-updated copy (`true`) or the bundled sidecar.
 */
export type YtdlpStatus = { version: string, updated: boolean, };
