import { expect, test } from "@playwright/test";
import { readFileSync } from "node:fs";
import { nativeSeekTarget } from "../src/lib/native-seek-target";

// Generated by video-sidecar/smoke_shots.py: 24 red frames then 24 blue,
// 24000/1001 fps. This opt-in never scans or substitutes user footage.
const fixture = process.env.NATIVE_SEEK_FIXTURE;
// Skipped at file scope: an in-body skip runs after the page fixture has
// already launched WebKit, which CI does not install.
test.skip(!fixture, "Supply the generated red/blue smoke_shots fixture");
test.use({ browserName: "webkit" });
test("native fractional-cut seeks show the first frame of the new shot", async ({ page }) => {
  await page.setContent('<video muted preload="auto"></video><canvas width="64" height="64"></canvas>');
  await page.locator("video").evaluate((video: HTMLVideoElement, src) => new Promise<void>(resolve => {
    video.onloadeddata = () => resolve();
    video.src = src;
  }), `data:video/mp4;base64,${readFileSync(fixture!).toString("base64")}`);
  const dimensions = await page.locator("video").evaluate((video: HTMLVideoElement) => [video.videoWidth, video.videoHeight, video.duration]);
  expect(dimensions).toEqual([64, 64, 2.002]);
  for (const [seconds, expectedColor] of [[0.5, "red"], [1.001, "blue"], [0, "red"], [1.001, "blue"]] as const) {
    const result = await page.evaluate(async target => {
      const video = document.querySelector("video")!;
      await new Promise<void>(resolve => {
        video.addEventListener("seeked", () => resolve(), { once: true });
        video.currentTime = target;
      });
      await new Promise(requestAnimationFrame);
      const context = document.querySelector("canvas")!.getContext("2d")!;
      context.drawImage(video, 0, 0, 64, 64);
      return { time: video.currentTime, rgba: Array.from(context.getImageData(32, 32, 1, 1).data) };
    }, nativeSeekTarget(seconds, 2.002));
    expect(result.time).toBeCloseTo(seconds, 6);
    const [red, , blue] = result.rgba;
    expect(expectedColor === "red" ? red - blue : blue - red).toBeGreaterThan(150);
  }
});
