// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { multitrackFixture, multitrackGroupFixture, multitrackTranscript } from "../test/multitrack-fixture";
import { MultitrackWorkspace } from "./MultitrackWorkspace";
const mocks = vi.hoisted(() => ({ start: vi.fn(), stop: vi.fn(), seek: vi.fn().mockResolvedValue(undefined), pause: vi.fn(), toggle: vi.fn(), shuttle: vi.fn() }));
vi.mock("../hooks/use-multitrack-transcription", () => ({ useMultitrackTranscription: () => ({ engine: "parakeet", models: [], ready: true, loading: false, status: "", error: null, resolution: null, ...mocks }) }));
vi.mock("../hooks/use-multitrack-audition", () => ({ useMultitrackAudition: () => ({ ...mocks, frame: 0, rate: 0, solo: new Set(), mute: new Set(), scrubbing: true, volume: .8, muted: false }) }));
vi.mock("../hooks/use-multitrack-detail", () => ({ useMultitrackDetail: () => ({}) }));
vi.mock("./MultitrackCast", () => ({ MultitrackCast: () => <div>Save Mic Owners as Cast</div> }));
vi.mock("./MultitrackTranscript", () => ({ MultitrackTranscript: () => null }));
beforeEach(() => { vi.clearAllMocks(); localStorage.clear(); });
afterEach(cleanup);
it("group disclosure never selects an alternative or starts playback/transcription", () => {
  const visible = vi.fn();
  render(<MultitrackWorkspace document={multitrackGroupFixture()} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} onVisibleTracks={visible} />);
  expect(screen.queryByRole("checkbox", { name: "Select Sam mic" })).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "Alternative microphones for A1" }));
  expect((screen.getByRole("checkbox", { name: "Select Sam mic" }) as HTMLInputElement).checked).toBe(false);
  expect(visible).toHaveBeenLastCalledWith(["track-1", "track-2", "track-3"]);
  expect(mocks.start).not.toHaveBeenCalled(); expect(mocks.toggle).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole("button", { name: "Generate 1 track" }));
  expect(mocks.start).toHaveBeenCalledWith(["track-1"], 0, 24000);
});
it("offline roots still reveal independently usable microphones", () => {
  const doc = multitrackGroupFixture(); doc.manifest.graph!.lanes[0].availability = "offline";
  render(<MultitrackWorkspace document={doc} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} />);
  expect((screen.getByRole("checkbox", { name: "Select Alex mic" }) as HTMLInputElement).disabled).toBe(true);
  expect(screen.getByText("Offline")).toBeTruthy();
  fireEvent.click(screen.getByRole("button", { name: "Alternative microphones for A1" }));
  fireEvent.click(screen.getByRole("checkbox", { name: "Select Sam mic" }));
  fireEvent.click(screen.getByRole("button", { name: "Generate 1 track" }));
  expect(mocks.start).toHaveBeenCalledWith(["track-2"], 0, 24000);
});
it("keeps offline saved tracks selectable for export without generating them", () => {
  const doc = multitrackGroupFixture(); doc.manifest.graph!.lanes[0].availability = "offline";
  doc.transcripts = [multitrackTranscript()];
  render(<MultitrackWorkspace document={doc} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} />);
  const offline = screen.getByRole("checkbox", { name: "Select Alex mic" }) as HTMLInputElement;
  expect(offline.disabled).toBe(false); expect(offline.checked).toBe(true);
  expect((screen.getByRole("button", { name: "Generate 0 tracks" }) as HTMLButtonElement).disabled).toBe(true);
  fireEvent.click(screen.getByRole("button", { name: "Alternative microphones for A1" }));
  fireEvent.click(screen.getByRole("checkbox", { name: "Select Sam mic" }));
  fireEvent.click(screen.getByRole("button", { name: "Generate 1 track" }));
  expect(mocks.start).toHaveBeenLastCalledWith(["track-2"], 0, 24000);
  fireEvent.click(screen.getByRole("button", { name: "Select all" }));
  expect(offline.checked).toBe(true);
  fireEvent.click(screen.getByRole("button", { name: "Deselect all" }));
  expect(offline.checked).toBe(false);
});
it("opens Clip-style digit entry from the number pad, ignores letters and seeks only on Enter", () => {
  render(<MultitrackWorkspace document={multitrackFixture()} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} />);
  expect(screen.getByRole("button", { name: "Current timecode" }).textContent).toBe("01:00:00:00");
  expect(screen.getByLabelText("Total runtime").textContent).toBe("TRT00:16:40:00");
  fireEvent.keyDown(window, { key: "0", code: "Numpad0", location: 3 });
  const dialog = screen.getByRole("dialog", { name: "Go to timecode" });
  expect(document.activeElement).toBe(dialog);
  for (const key of "1001012") fireEvent.keyDown(dialog, { key, code: `Numpad${key}`, location: 3 });
  expect(screen.getByLabelText("Entered timecode").textContent).toBe("01:00:10:12");
  for (const key of ["x", "j", "k", "l", " ", ".", "+"]) fireEvent.keyDown(dialog, { key });
  expect(screen.getByLabelText("Entered timecode").textContent).toBe("01:00:10:12");
  expect(mocks.seek).not.toHaveBeenCalled(); expect(mocks.shuttle).not.toHaveBeenCalled(); expect(mocks.pause).not.toHaveBeenCalled(); expect(mocks.toggle).not.toHaveBeenCalled();
  fireEvent.keyDown(dialog, { key: "Enter", code: "NumpadEnter", location: 3 });
  expect(mocks.seek).toHaveBeenCalledExactlyOnceWith(252, undefined, false);
  expect(screen.queryByRole("dialog")).toBeNull();
});
it("click entry supports correction, Escape and empty Enter without seeking, and restores focus", () => {
  render(<MultitrackWorkspace document={multitrackFixture()} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} />);
  const trigger = screen.getByRole("button", { name: "Current timecode" }); trigger.focus(); fireEvent.click(trigger);
  let dialog = screen.getByRole("dialog", { name: "Go to timecode" });
  for (const key of "123456789") fireEvent.keyDown(dialog, { key });
  expect(screen.getByLabelText("Entered timecode").textContent).toBe("23:45:67:89");
  fireEvent.keyDown(dialog, { key: "Backspace" });
  expect(screen.getByLabelText("Entered timecode").textContent).toBe("02:34:56:78");
  fireEvent.keyDown(dialog, { key: "Escape" }); expect(document.activeElement).toBe(trigger);
  fireEvent.click(trigger); dialog = screen.getByRole("dialog", { name: "Go to timecode" });
  fireEvent.keyDown(dialog, { key: "Enter" });
  expect(screen.queryByRole("dialog")).toBeNull(); expect(mocks.seek).not.toHaveBeenCalled();
});
it("does not steal numeric typing from fields, menus, modifiers, hidden views or settings", () => {
  const props = { document: multitrackFixture(), active: true, waveforms: {}, waveformErrors: {}, labelStatus: "", onRename: vi.fn(), onTranscript: vi.fn() };
  const { rerender } = render(<MultitrackWorkspace {...props} />);
  fireEvent.keyDown(screen.getByRole("textbox", { name: "Mic owner for track-1" }), { key: "1" });
  fireEvent.keyDown(window, { key: "1", metaKey: true });
  fireEvent.keyDown(window, { key: "1", isComposing: true });
  expect(screen.queryByRole("dialog")).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "Track actions for Alex" }));
  fireEvent.keyDown(window, { key: "1" }); expect(screen.queryByRole("dialog")).toBeNull();
  fireEvent.keyDown(screen.getByRole("menu", { name: "Actions for Alex" }), { key: "Escape" });
  fireEvent.keyDown(window, { key: "1" }); expect(screen.getByRole("dialog", { name: "Go to timecode" })).toBeTruthy();
  rerender(<MultitrackWorkspace {...props} active={false} />);
  fireEvent.keyDown(window, { key: "1" }); expect(screen.queryByRole("dialog")).toBeNull();
  rerender(<MultitrackWorkspace {...props} settingsOpen />);
  fireEvent.keyDown(window, { key: "1" }); expect(screen.queryByRole("dialog", { name: "Go to timecode" })).toBeNull();
  expect(mocks.seek).not.toHaveBeenCalled();
});
it("abandons uncommitted entry when the loaded document changes", () => {
  const props = { document: multitrackFixture(), active: true, waveforms: {}, waveformErrors: {}, labelStatus: "", onRename: vi.fn(), onTranscript: vi.fn() };
  const { rerender } = render(<MultitrackWorkspace {...props} />);
  fireEvent.keyDown(window, { key: "1" });
  rerender(<MultitrackWorkspace {...props} document={{ ...props.document, id: "another-document" }} />);
  expect(screen.queryByRole("dialog", { name: "Go to timecode" })).toBeNull(); expect(mocks.seek).not.toHaveBeenCalled();
});
it("keeps an invalid drop-frame entry open for correction instead of seeking another frame", () => {
  const doc = multitrackFixture();
  doc.manifest = { ...doc.manifest, edit_rate: { numerator: 30000, denominator: 1001 }, start_frame: 107892, drop_frame: true };
  render(<MultitrackWorkspace document={doc} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} />);
  fireEvent.click(screen.getByRole("button", { name: "Current timecode" }));
  const dialog = screen.getByRole("dialog", { name: "Go to timecode" });
  for (const key of "01010000") fireEvent.keyDown(dialog, { key });
  fireEvent.keyDown(dialog, { key: "Enter" });
  expect(screen.getByRole("alert").textContent).toContain("skipped in drop-frame"); expect(mocks.seek).not.toHaveBeenCalled();
  fireEvent.keyDown(dialog, { key: "Backspace" }); fireEvent.keyDown(dialog, { key: "2" });
  expect(screen.queryByRole("alert")).toBeNull();
  expect(screen.getByLabelText("Entered timecode").textContent).toBe("01:01:00;02");
  fireEvent.keyDown(dialog, { key: "Enter" }); expect(mocks.seek).toHaveBeenCalledExactlyOnceWith(1800, undefined, false);
});
it("Generate starts the whole sequence without a mic confirmation, from checked tracks only", () => {
  const document = multitrackFixture();
  render(<MultitrackWorkspace document={document} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} />);
  expect(screen.queryByText(/I reviewed the mic labels/)).toBeNull();
  expect(screen.queryByLabelText(/Start \(seconds\)/)).toBeNull();
  const button = screen.getByRole("button", { name: "Generate 3 tracks" }) as HTMLButtonElement;
  expect(button.disabled).toBe(false); fireEvent.click(button);
  expect(mocks.start).toHaveBeenCalledWith(["track-1", "track-2", "track-3"], 0, document.manifest.duration_frames);
  fireEvent.click(screen.getByRole("checkbox", { name: "Select Sam mic" }));
  fireEvent.click(screen.getByRole("button", { name: "Generate 2 tracks" }));
  expect(mocks.start).toHaveBeenLastCalledWith(["track-1", "track-3"], 0, document.manifest.duration_frames);
});
it("JKL belongs to the active timeline, never editable mic names", () => {
  render(<MultitrackWorkspace document={multitrackFixture()} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} />);
  fireEvent.keyDown(window, { key: "l" }); expect(mocks.shuttle).toHaveBeenCalledWith(1);
  fireEvent.keyDown(window, { key: "k" }); expect(mocks.pause).toHaveBeenCalled();
  fireEvent.keyDown(window, { key: "j" }); expect(mocks.seek).toHaveBeenCalledWith(-1, undefined, false);
  fireEvent.keyUp(window, { key: "k" }); mocks.shuttle.mockClear();
  fireEvent.keyDown(screen.getByRole("textbox", { name: "Mic owner for track-1" }), { key: "l" });
  expect(mocks.shuttle).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole("button", { name: "Track actions for Alex" }));
  fireEvent.keyDown(screen.getByRole("menu", { name: "Actions for Alex" }), { key: "l" });
  expect(mocks.shuttle).not.toHaveBeenCalled();
});
it("rewind and fast-forward buttons use the same shuttle controls as J and L", () => {
  render(<MultitrackWorkspace document={multitrackFixture()} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} />);
  fireEvent.click(screen.getByRole("button", { name: "Rewind tracks" })); expect(mocks.shuttle).toHaveBeenLastCalledWith(-1);
  fireEvent.click(screen.getByRole("button", { name: "Fast-forward tracks" })); expect(mocks.shuttle).toHaveBeenLastCalledWith(1);
});
it("Escape abandons an edited mic name without committing it on blur", () => {
  const rename = vi.fn();
  render(<MultitrackWorkspace document={multitrackFixture()} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={rename} onTranscript={vi.fn()} />);
  const input = screen.getByRole("textbox", { name: "Mic owner for track-1" }) as HTMLInputElement;
  input.focus(); fireEvent.change(input, { target: { value: "Cancelled owner" } });
  fireEvent.keyDown(input, { key: "Escape" });
  expect(input.value).toBe("Alex"); expect(rename).not.toHaveBeenCalled();
  input.focus(); fireEvent.change(input, { target: { value: "Saved owner" } }); fireEvent.keyDown(input, { key: "Enter" });
  expect(rename).toHaveBeenCalledWith("track-1", "Saved owner");
});
it("Select all includes collapsed alternatives; Option-click sets one group and Option-disclosure opens every group", () => {
  const doc = multitrackGroupFixture();
  render(<MultitrackWorkspace document={doc} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} />);
  fireEvent.click(screen.getByRole("button", { name: "Select all" }));
  fireEvent.click(screen.getByRole("button", { name: "Generate 3 tracks" }));
  expect(mocks.start).toHaveBeenLastCalledWith(["track-1", "track-2", "track-3"], 0, 24000);
  fireEvent.click(screen.getByRole("button", { name: "Deselect all" }));
  fireEvent.click(screen.getByRole("checkbox", { name: "Select Alex mic" }), { altKey: true });
  fireEvent.click(screen.getByRole("button", { name: "Generate 3 tracks" }));
  expect(mocks.start).toHaveBeenLastCalledWith(["track-1", "track-2", "track-3"], 0, 24000);
  fireEvent.click(screen.getByRole("checkbox", { name: "Select Alex mic" }), { altKey: true });
  expect((screen.getByRole("button", { name: "Generate 0 tracks" }) as HTMLButtonElement).disabled).toBe(true);
  fireEvent.click(screen.getByRole("checkbox", { name: "Select Alex mic" }));
  fireEvent.click(screen.getByRole("button", { name: "Generate 1 track" }));
  expect(mocks.start).toHaveBeenLastCalledWith(["track-1"], 0, 24000);
  const disclosure = screen.getByRole("button", { name: "Alternative microphones for A1" });
  fireEvent.click(disclosure, { altKey: true });
  expect(disclosure.getAttribute("aria-expanded")).toBe("true");
  expect(screen.getByRole("checkbox", { name: "Select Sam mic" })).toBeTruthy();
  fireEvent.click(disclosure, { altKey: true });
  expect(screen.queryByRole("checkbox", { name: "Select Sam mic" })).toBeNull();
});
it("reopening a sequence restores its zoom, track size, open groups, checked mics and waveform toggle", () => {
  const doc = multitrackGroupFixture();
  const first = render(<MultitrackWorkspace document={doc} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} />);
  fireEvent.click(screen.getByRole("button", { name: "Zoom in" }));
  fireEvent.click(screen.getByRole("button", { name: "Alternative microphones for A1" }));
  fireEvent.click(screen.getByRole("checkbox", { name: "Select Sam mic" }));
  fireEvent.click(screen.getByRole("button", { name: "Waveforms" }));
  first.unmount();
  render(<MultitrackWorkspace document={doc} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} />);
  expect(screen.getByText("2×")).toBeTruthy();
  expect((screen.getByRole("checkbox", { name: "Select Sam mic" }) as HTMLInputElement).checked).toBe(true);
  expect(screen.getByRole("button", { name: "Waveforms" }).getAttribute("aria-pressed")).toBe("false");
});
it("I/O marks switch generation to the marked range and G returns it to the whole sequence", () => {
  render(<MultitrackWorkspace document={multitrackFixture()} active waveforms={{}} waveformErrors={{}} labelStatus="" onRename={vi.fn()} onTranscript={vi.fn()} />);
  const scope = screen.getByRole("combobox", { name: "Transcription range" }) as HTMLSelectElement;
  expect(scope.value).toBe("all");
  fireEvent.keyDown(window, { key: "o" });
  expect(scope.value).toBe("marked");
  expect(scope.selectedOptions[0].textContent).toBe("Marked range 01:00:00:00 to 01:00:00:00");
  fireEvent.click(screen.getByRole("button", { name: /^Generate/ }));
  expect(mocks.start).toHaveBeenLastCalledWith(expect.any(Array), 0, 1);
  fireEvent.change(scope, { target: { value: "all" } });
  fireEvent.click(screen.getByRole("button", { name: /^Generate/ }));
  expect(mocks.start).toHaveBeenLastCalledWith(expect.any(Array), 0, 24000);
  fireEvent.keyDown(window, { key: "i" });
  expect(scope.value).toBe("marked");
  fireEvent.keyDown(window, { key: "g" });
  expect(scope.value).toBe("all");
  expect((scope.options[1] as HTMLOptionElement).disabled).toBe(true);
});
