/**
 * Shared type definitions for the Sauce Bunny frontend.
 *
 * The Rust-side types live in `src/bindings/*.ts`, auto-generated by
 * the `ts-rs` crate from the canonical `#[derive(TS)]` structs in
 * `src-tauri/src/commands/`. Run `cargo test --lib` from `src-tauri/`
 * to refresh them. See CLAUDE.md refactor priority #3 (r49).
 *
 * This file:
 *   - Re-exports those generated types so consumers can import from
 *     a single, stable location (`./types`) regardless of where the
 *     definition actually lives.
 *   - Adds frontend-only types that have no Rust counterpart
 *     (form state, UI status enums, localStorage shapes).
 */

// ── Generated from Rust (single source of truth) ────────────────────
export type { AppError } from "./bindings/AppError";
export type { CacheStats } from "./bindings/CacheStats";
export type { DiarizeProgressEvent } from "./bindings/DiarizeProgressEvent";
export type { DictateDoneEvent } from "./bindings/DictateDoneEvent";
export type { DictateLevelEvent } from "./bindings/DictateLevelEvent";
export type { DictatePartialEvent } from "./bindings/DictatePartialEvent";
export type { AudioInputDevice } from "./bindings/AudioInputDevice";
export type { DoneEvent } from "./bindings/DoneEvent";
export type { LibraryFolder } from "./bindings/LibraryFolder";
export type { LibraryItem } from "./bindings/LibraryItem";
export type { LibraryItemKind } from "./bindings/LibraryItemKind";
export type { LocalFileMeta } from "./bindings/LocalFileMeta";
export type { LogEvent } from "./bindings/LogEvent";
export type { Metadata } from "./bindings/Metadata";
export type { CacheCategoryStats } from "./bindings/CacheCategoryStats";
export type { CachedStream } from "./bindings/CachedStream";
export type { WarmStart } from "./bindings/WarmStart";
/** Kept under the legacy frontend name; the Rust struct is `ModelProgressEvent`. */
export type { ModelProgressEvent as ModelDownloadEvent } from "./bindings/ModelProgressEvent";
export type { ProgressEvent } from "./bindings/ProgressEvent";
export type { TranscriptPhaseEvent } from "./bindings/TranscriptPhaseEvent";
export type { WhisperModel } from "./bindings/WhisperModel";

// ── Frontend-only — no Rust counterpart ────────────────────────────
// These describe React state, form input, or display-side enums that
// never cross the invoke boundary.

/** Narrowing of `LogEvent.tag` — Rust ships it as `string`, but only
 *  ever emits one of these five values, so we narrow at the boundary. */
export type LogTag = "info" | "ok" | "warn" | "err" | "muxer";

/** Boundary narrowing for an incoming `LogEvent.tag`. Returns the
 *  matching `LogTag` literal, or `"info"` for unknown strings (never
 *  expected — defensive against a Rust-side enum addition). */
export function asLogTag(s: string): LogTag {
  return (s === "ok" || s === "warn" || s === "err" || s === "muxer")
    ? s
    : "info";
}

export type AppStatus =
  | "empty"
  | "fetching"
  | "loaded"
  | "exporting"
  | "success"
  | "error";

export type FormatId = "4k" | "1080" | "720" | "audio";

export type ExportOpts = {
  inTc: string;
  outTc: string;
  filename: string;
  folder: string | null;
  format: FormatId;
  captions: boolean;
  reencode: boolean;
};

export type RecentClip = {
  id: string;
  title: string;
  path: string;
  dur: string;
  when: number; // epoch ms
  thumbnail: string | null;
  /** Source identity (webpage URL or local file path). Grouping in the
   *  sidebar keys on this — titles are display-only and can collide
   *  (review fix). Optional: legacy entries fall back to the title. */
  source?: string;
};


export type QueueStatus = "queued" | "running" | "done" | "error";

/** Where a queued clip reads its media from — captured at ADD time so the
 *  queue runner never depends on the currently-loaded source (the queue
 *  survives source switches; mixed web+local queues just work). */
export type QueueSource =
  | { kind: "web"; url: string }
  | { kind: "file"; path: string };

export type QueuedClip = {
  id: string;
  source: QueueSource;
  /** Source fps at add time — ALL frames→seconds/tc math for this item must
   *  use it, never the live player fps (which may belong to another source). */
  fps: number;
  /** Title + thumbnail at add time — recents attribution for mixed/stale queues. */
  title: string;
  thumbnail: string | null;
  inFrames: number;
  outFrames: number;
  filename: string;
  format: FormatId;
  /** Web-only (yt-dlp re-encode); local items set false — mediabunny decides
   *  passthrough vs re-encode itself. */
  reencode: boolean;
  /** Web-only (yt-dlp subtitles); always false for file items. */
  captions: boolean;
  status: QueueStatus;
  path?: string;
  error?: string;
};

export type SourceKind = "youtube" | "file";

export type ClientLog = {
  id: number;
  ts: string;          // HH:MM:SS
  tag: LogTag;
  source: string;      // e.g. "yt-dlp", "ffmpeg", "probe", "ok", "warn"
  message: string;
};

/**
 * The in-progress comment range drawn on the timeline.
 *
 * Two shapes on purpose. `live` carries only the ANCHOR — the edge the user
 * has marked — and the band's other end is wherever the playhead is right
 * now, read by the timeline itself. That is what keeps a scrub from
 * re-rendering the App tree at source fps while someone hunts the out point.
 * Once both ends are marked the band is fixed and needs no clock at all.
 */
export type ReviewRangeDraft =
  | { live: true; anchor: number; color: string }
  | { live: false; start: number; end: number; color: string };
