/**
 * Shared type definitions for the Sauce Bunny frontend.
 *
 * The Rust-side types live in `src/bindings/*.ts`, auto-generated by
 * the `ts-rs` crate from the canonical `#[derive(TS)]` structs in
 * `src-tauri/src/commands/`. Run `cargo test --lib` from `src-tauri/`
 * to refresh them. See CLAUDE.md refactor priority #3 (r49).
 *
 * This file:
 *   - Re-exports those generated types so consumers can import from
 *     a single, stable location (`./types`) regardless of where the
 *     definition actually lives.
 *   - Adds frontend-only types that have no Rust counterpart
 *     (form state, UI status enums, localStorage shapes).
 */

// ── Generated from Rust (single source of truth) ────────────────────
export type { AppError } from "./bindings/AppError";
export type { CacheStats } from "./bindings/CacheStats";
export type { DiarizeProgressEvent } from "./bindings/DiarizeProgressEvent";
export type { DoneEvent } from "./bindings/DoneEvent";
export type { LocalFileMeta } from "./bindings/LocalFileMeta";
export type { LogEvent } from "./bindings/LogEvent";
export type { Metadata } from "./bindings/Metadata";
/** Kept under the legacy frontend name; the Rust struct is `ModelProgressEvent`. */
export type { ModelProgressEvent as ModelDownloadEvent } from "./bindings/ModelProgressEvent";
export type { ProgressEvent } from "./bindings/ProgressEvent";
export type { TranscriptPhaseEvent } from "./bindings/TranscriptPhaseEvent";
export type { WhisperModel } from "./bindings/WhisperModel";

// ── Frontend-only — no Rust counterpart ────────────────────────────
// These describe React state, form input, or display-side enums that
// never cross the invoke boundary.

/** Narrowing of `LogEvent.tag` — Rust ships it as `string`, but only
 *  ever emits one of these five values, so we narrow at the boundary. */
export type LogTag = "info" | "ok" | "warn" | "err" | "muxer";

/** Boundary narrowing for an incoming `LogEvent.tag`. Returns the
 *  matching `LogTag` literal, or `"info"` for unknown strings (never
 *  expected — defensive against a Rust-side enum addition). */
export function asLogTag(s: string): LogTag {
  return (s === "ok" || s === "warn" || s === "err" || s === "muxer")
    ? s
    : "info";
}

export type AppStatus =
  | "empty"
  | "fetching"
  | "loaded"
  | "exporting"
  | "success"
  | "error";

export type FormatId = "4k" | "1080" | "720" | "audio";

export type ExportOpts = {
  inTc: string;
  outTc: string;
  filename: string;
  folder: string | null;
  format: FormatId;
  captions: boolean;
  reencode: boolean;
};

export type RecentClip = {
  id: string;
  title: string;
  path: string;
  dur: string;
  when: number; // epoch ms
  thumbnail: string | null;
};

export type TranscriptState = "idle" | "running" | "done" | "error";

export type QueueStatus = "queued" | "running" | "done" | "error";

export type QueuedClip = {
  id: string;
  inFrames: number;
  outFrames: number;
  filename: string;
  format: FormatId;
  reencode: boolean;
  captions: boolean;
  status: QueueStatus;
  path?: string;
  error?: string;
};

export type SourceKind = "youtube" | "file";

export type ClientLog = {
  id: number;
  ts: string;          // HH:MM:SS
  tag: LogTag;
  source: string;      // e.g. "yt-dlp", "ffmpeg", "probe", "ok", "warn"
  message: string;
};
