/**
 * Source-backed inventory for the isolated design catalog.
 * Families record their adoption status; unapproved proposals stay catalog-only.
 * Keep paths repository-relative so the catalog can link to the inspected code.
 */
export type CatalogGroup = "Controls" | "Specialty" | "Content" | "Navigation" | "Surfaces" | "Review";
export type CatalogWorkspace = "Home" | "Library" | "Clip" | "Review" | "Transcripts" | "Settings" | "Dialogs" | "Detached";
export type CatalogClassification = "keep" | "standardize" | "intentional exception" | "functional defect";

export type CatalogEntry = {
  id: string;
  title: string;
  group: CatalogGroup;
  workspaces: CatalogWorkspace[];
  classification: CatalogClassification;
  current: string;
  proposed: string;
  sources: { path: string; note: string }[];
  rules: string[];
};

const everyWorkspace: CatalogWorkspace[] = ["Home", "Library", "Clip", "Review", "Transcripts", "Settings", "Dialogs", "Detached"];

export const catalogEntries: CatalogEntry[] = [
  {
    id: "generate",
    title: "Generate transcript + speakers",
    group: "Specialty",
    workspaces: ["Clip", "Transcripts"],
    classification: "intentional exception",
    current: "GenerateButton is the actual signature transcription CTA: three curved sparkles, letter layers, beveled green wash, progress underfill and Done/Failed resolution. Sidebar selects Generate transcript + speakers or Generate transcript; retries and reruns have their own labels. A bare .cp-gen-btn element is not this component.",
    proposed: "Retain the production component and its exact visual treatment. Inspect real idle, loading, progress, disabled, success and error states using isolated fixture props. The 30px/26px command selector does not resize specialty actions. Generation, cancellation and model selection remain parent-owned.",
    sources: [
      { path: "src/components/GenerateButton.tsx", note: "Imported production component, including sparkle SVG, label layers, progress and polite result announcement." },
      { path: "src/components/Sidebar.tsx", note: "Detect speakers option, expected-speaker count and exact combined/transcript/retry labels." },
      { path: "src/styles/buttons.css", note: "cp-gen-* geometry, green wash, animated states and reduced-motion branch." },
      { path: "src/components/Sidebar.test.tsx", note: "Existing caller tests; fixture controls never invoke real jobs." },
    ],
    rules: [
      "Reuse GenerateButton for this specialty action; do not substitute a plain button with its CSS class.",
      "Keep the three-sparkle artwork, existing color semantics and layered state feedback.",
      "The parent passes loading, progress, resolution, disabled and onResolved; the component does not start a job.",
      "Keep loading disabled at the caller and provide cancellation separately.",
      "Preserve reduced motion. Long labels and enlarged text need measured tests before changing the production geometry.",
    ],
  },
  {
    id: "speakers",
    title: "Speaker controls",
    group: "Specialty",
    workspaces: ["Clip", "Transcripts", "Dialogs", "Detached"],
    classification: "intentional exception",
    current: "Speaker UI is several different patterns: Detect speakers is a checkbox configuring the combined job, Expected speakers is a native select, Speakers is a transcript-library filter, Manage opens the roster, Speaker insights opens a rich popover, and speaker-only detection lives in Tools. Identity chips and assignments are not interchangeable with job buttons.",
    proposed: "Keep those distinct roles and show their source-markup fixtures with local data. Preserve the actual toolbar and menu treatments, speaker identity colors, labeling, disclosure state and keyboard helpers. Do not invent a speakers-only Generate CTA that the app does not have.",
    sources: [
      { path: "src/components/Sidebar.tsx", note: "Detect speakers checkbox and Expected speakers configuration before generation." },
      { path: "src/components/TranscriptViewer.tsx", note: "Speakers roster, Speaker insights and Tools detection commands." },
      { path: "src/components/TranscriptReader.tsx", note: "Speakers is a pressed filter chip in the transcript library, not the roster action." },
      { path: "src/components/transcript/SpeakerRosterModal.tsx", note: "Speaker identity management and dialog semantics." },
      { path: "src/components/transcript/SpeakerRosterRow.tsx", note: "Rename, color, selection and preview actions have separate roles." },
      { path: "src/components/transcript/InsightsPopover.tsx", note: "Speaker insights content and rich-popover behavior." },
      { path: "src/styles/transcript.css", note: "Speaker chips, toolbar actions and insights styling." },
    ],
    rules: [
      "Name each action by intent: configure detection, run detection, open roster, inspect, or assign a speaker.",
      "Do not use a passive status badge as a speaker assignment or roster command.",
      "Use native checkbox/select semantics for configuration and existing focus/dismiss helpers for surfaces.",
      "Keep speaker identity distinct from violet selection and green live/success feedback.",
      "Fixtures are not a second transcript editor and never load saved transcripts or models.",
    ],
  },
  {
    id: "buttons",
    title: "Action buttons",
    group: "Controls",
    workspaces: everyWorkspace,
    classification: "standardize",
    current: "The shared .btn family is 30px high, neutral and beveled. Primary means stronger neutral emphasis. Compact mixes 22px height with uppercase 10px text; context selectors add more sizes. Most commands are raw button elements rather than shared components.",
    proposed: "Review a 30px default and 26px compact recipe with independent emphasis and density. Use a small native Button API, preserving existing CSS aliases during later adoption. Keep Play, imagery overlays and branded async actions as named exceptions.",
    sources: [
      { path: "src/styles/buttons.css", note: "Shared .btn, primary, ghost, compact and armed recipes." },
      { path: "src/components/Toolbar.tsx", note: "Import, clear and fetch commands." },
      { path: "src/components/SettingsModal.tsx", note: "Ordinary actions and second-click destructive confirmation." },
      { path: "src/lib/button-variant-contract.test.ts", note: "Existing guard catches border drift, not a complete recipe contract." },
    ],
    rules: [
      "Default to a native type=button; keep form submission explicit.",
      "Do not make a command green simply because it is primary or available.",
      "Keep size separate from uppercase text, tone and interaction semantics.",
      "Document 22px legacy controls as migration candidates, not the new default.",
    ],
  },
  {
    id: "icons",
    title: "Icon actions and close controls",
    group: "Controls",
    workspaces: everyWorkspace,
    classification: "standardize",
    current: "The beveled 30px .btn-icon, borderless 30×28px transport utilities, 24px queue actions and 26px review actions serve related but not identical contexts. Close buttons still vary. Fixing SVG size alone previously allowed whole review buttons to shrink.",
    proposed: "Review standard and compact IconButton recipes with an explicit accessible label, fixed hitbox and non-shrinking icon. Preserve separate imagery-overlay and transport recipes instead of flattening every icon into one visual surface.",
    sources: [
      { path: "src/components/Icons.tsx", note: "Shared SVG artwork uses currentColor and explicit sizes." },
      { path: "src/styles/transport.css", note: "Transport play controls and borderless utility family." },
      { path: "src/styles/review.css", note: "Fixed review action hitboxes and composer tool variants." },
      { path: "src/styles/queue-drawer.css", note: "Dense queue and detached-panel icon actions." },
      { path: "src/lib/hit-target-contract.test.ts", note: "Small-target ratchet has static extraction limitations." },
    ],
    rules: [
      "Size the hitbox separately from the glyph and prevent flex compression.",
      "Every icon action needs a name describing its actual action.",
      "A 24px minimum target or measured spacing exception is required; screenshots of glyphs alone are insufficient.",
      "Keyboard focus must reveal hover-only imagery actions.",
    ],
  },
  {
    id: "statuses",
    title: "Status, identity and passive readouts",
    group: "Content",
    workspaces: ["Home", "Library", "Clip", "Review", "Transcripts", "Settings", "Detached"],
    classification: "standardize",
    current: "Live now uses the adopted content-sized .cp-source-status recipe; neighboring Premiere uses .cp-toolbar-disclosure. Room role badges, job outcomes, connection states, source metadata and person colors have different meanings even when all appear as small pills.",
    proposed: "Keep the approved passive Preview status and disclosure separate. The broader StatusBadge vocabulary remains a catalog proposal. Keep numeric timecode as its own readout and identity as identity; live status never implies zero latency or verified sequence timing.",
    sources: [
      { path: "src/components/Transport.tsx", note: "Adopted content-sized Live status; file timecode retains its dedicated numeric readout." },
      { path: "src/components/ReviewStatusChip.tsx", note: "Existing document status display; cataloging it does not add an approval workflow." },
      { path: "src/components/PeoplePanel.tsx", note: "Host, presenter, recording and raised-hand semantics." },
      { path: "src/styles/tokens.css", note: "Semantic success, warning and danger colors; selection is a separate role." },
    ],
    rules: [
      "Do not style a passive status as a disabled command.",
      "Use words or icons as well as color to identify state.",
      "Keep success, live feed, recording, selection and identity conceptually separate.",
      "A live label must not promise verified sequence timecode or measured zero latency.",
    ],
  },
  {
    id: "fields",
    title: "Fields, search and validation",
    group: "Controls",
    workspaces: everyWorkspace,
    classification: "functional defect",
    current: "URL/search wrappers, settings inputs, session fields, timecode entry and review composition reuse tokens but not a single field contract. Sidebar Filename has an adjacent unassociated label; some timecode validation is visual without an accessible error relationship.",
    proposed: "Review Field and FieldMessage compositions around existing native inputs. Preserve specialized numeric/timecode parsing and composer behavior; standardize labels, help, error association and wrapper focus without changing data formats.",
    sources: [
      { path: "src/components/Toolbar.tsx", note: "Composed URL field with action controls." },
      { path: "src/components/Sidebar.tsx", note: "Filename and source-frame/timecode fields." },
      { path: "src/components/CoReviewLobby.tsx", note: "Session title, identity and join fields." },
      { path: "src/components/review/LabelInput.tsx", note: "Nested review input specialization." },
      { path: "src/styles/base.css", note: "White focus treatment and composed-field conventions." },
    ],
    rules: [
      "Associate every visible label with its control; a placeholder is not a label.",
      "Expose invalid state and connect error text with aria-describedby.",
      "Focus belongs to the whole composed field, not a second ring on its inner input.",
      "Never change persisted frame values while standardizing field presentation.",
    ],
  },
  {
    id: "selects",
    title: "Native selects and device pickers",
    group: "Controls",
    workspaces: ["Library", "Clip", "Review", "Transcripts", "Settings", "Dialogs", "Detached"],
    classification: "keep",
    current: "The shared .cp-select already controls native appearance, chevron, disabled state and 30/26/22px sizes. DeviceSelect is a real shared component, including positional labels when browser permissions hide device names.",
    proposed: "Retain native selects elsewhere. Expected speakers is the approved exception: a production controlled radio menu with deep-violet selection, viewport containment and the shared keyboard/focus behavior.",
    sources: [
      { path: "src/styles/buttons.css", note: "Shared .cp-select and sm/xs variants." },
      { path: "src/components/DeviceSelect.tsx", note: "Shared labeled camera/microphone picker." },
      { path: "src/components/ExpectedSpeakersMenu.tsx", note: "Scoped production radio-menu exception for brand-consistent selected fill." },
      { path: "src/components/LibraryBrowserBar.tsx", note: "Sort/select alignment with toolbar actions." },
      { path: "src/lib/select-contract.test.ts", note: "Existing native-select styling contract." },
    ],
    rules: [
      "Do not replace native selects with custom menus just to restyle them.",
      "Preserve keyboard interaction and usable labels before device permission is granted.",
      "Keep label, chosen value, unavailable device and disabled states distinct.",
    ],
  },
  {
    id: "choices",
    title: "Switches, radios and swatches",
    group: "Controls",
    workspaces: ["Library", "Clip", "Review", "Transcripts", "Settings", "Dialogs"],
    classification: "standardize",
    current: "Settings switches correctly expose role=switch and aria-checked. Segmented choices and ColorSwatches have separate visual/selection conventions; the latter is a shared radiogroup with a native custom color well. The switch track itself is only 18px tall.",
    proposed: "Catalog checkboxes use a 13px native glyph inside a clickable 26px label; production checkbox recipes are unchanged. Document switch, single-choice group and color-choice recipes separately. Review selected/focused distinctions, keyboard navigation and actual pointer spacing before choosing a common density treatment.",
    sources: [
      { path: "src/components/ColorSwatches.tsx", note: "Shared preset dots and exact custom color input." },
      { path: "src/components/SettingsModal.tsx", note: "Switches and mutually exclusive settings choices." },
      { path: "src/components/AvSettingsPane.tsx", note: "Camera, microphone and echo-cancellation switches." },
      { path: "src/styles/sidebar.css", note: "Switch geometry and track/thumb motion." },
    ],
    rules: [
      "A switch changes a persistent setting; a radio group chooses one value; neither is a tab.",
      "Do not communicate selected and keyboard-focused state with the same single ring.",
      "Retain exact custom colors and existing identity values.",
      "Measure the interactive area, not just the painted track or swatch.",
    ],
  },
  {
    id: "tabs",
    title: "Workspace and panel tabs",
    group: "Navigation",
    workspaces: ["Library", "Clip", "Review", "Transcripts", "Settings", "Dialogs", "Detached"],
    classification: "functional defect",
    current: "Drawer tabs, Settings tabs, browser shelf tabs and Host/Join selectors have different layouts. Some expose tab roles without the expected arrow-key navigation. Drawer tabs also support drag reordering, which a generic visual replacement must preserve.",
    proposed: "Review one selected-state vocabulary and a keyboard-complete tab composition. Keep compact tab bars distinct from form choices and primary navigation. Preserve mounted panel state and drag affordances.",
    sources: [
      { path: "src/components/QueueDrawer.tsx", note: "Draggable shared drawer tabs, including detached windows." },
      { path: "src/components/SettingsModal.tsx", note: "Settings tab navigation." },
      { path: "src/components/CoReviewLobby.tsx", note: "Host/Join selected forms preserve entered values." },
      { path: "src/lib/tab-state.ts", note: "Persisted tab state, not a keyboard interaction primitive." },
    ],
    rules: [
      "Tab roles require associated panels and a complete keyboard model.",
      "Keep selected, focus and hover states distinguishable.",
      "Switching a tab must not remount the player or discard a draft.",
      "Do not remove drag reordering while unifying appearance.",
    ],
  },
  {
    id: "menus",
    title: "Menus and anchored popovers",
    group: "Surfaces",
    workspaces: everyWorkspace,
    classification: "functional defect",
    current: "Most menus share useDismiss and useMenuKeys, but markup and surface recipes still vary. Nested transcript HistoryPopover declares role=menu and supports dismissal without useMenuKeys. Source and scope matter: non-recursive source scans miss nested components.",
    proposed: "Review a shared anchored surface plus separate menu behavior. Inventory nested sources recursively and preserve native links, menuitem radios, selection menus and rich popovers as distinct content types.",
    sources: [
      { path: "src/hooks/use-menu-keys.ts", note: "Existing menu keyboard/focus behavior to reuse." },
      { path: "src/hooks/use-dismiss.ts", note: "Escape, outside interaction and app-level dismissal seam." },
      { path: "src/components/SourceShareMenu.tsx", note: "Preview source actions and permission-sensitive sharing choices." },
      { path: "src/components/transcript/HistoryPopover.tsx", note: "Nested history menu with incomplete menu keyboard behavior." },
      { path: "src/components/transcript/CueSelectionMenu.tsx", note: "Nested transcript-selection actions." },
    ],
    rules: [
      "Not every popover is a menu; assign roles from behavior, not appearance.",
      "Escape closes and focus returns to the originating control.",
      "Portals or equivalent positioning must escape clipping ancestors.",
      "Opening a modal must not leave interactive menus above its scrim.",
    ],
  },
  {
    id: "tooltips",
    title: "Tooltips and action names",
    group: "Surfaces",
    workspaces: everyWorkspace,
    classification: "functional defect",
    current: "Native title is the default. The shared Tooltip is intentionally limited to crowded rows where the bubble must clear the pointer. Volume's muted-state tooltip says Unmute even though primary click opens its popover; dynamic names escape the literal-only naming check.",
    proposed: "Keep native titles by default and the existing positioned exception. Review consistent action naming, shortcut hints and pointer/focus dismissal; fix mismatched action text later without inventing a second tooltip framework.",
    sources: [
      { path: "src/components/Tooltip.tsx", note: "Above-control tooltip with focus, Escape and viewport handling." },
      { path: "src/components/VolumeControl.tsx", note: "Popover trigger and separate actual mute control." },
      { path: "src/components/ReviewPanel.tsx", note: "Crowded composer tools use the positioned tooltip." },
      { path: "src/lib/control-naming-contract.test.ts", note: "Static title/aria-label comparison does not cover dynamic expressions." },
    ],
    rules: [
      "Describe what activating the control does, not merely its current state.",
      "Keep accessible names on the control; a decorative tooltip must not replace them.",
      "A tooltip must not cover adjacent controls or escape the viewport.",
    ],
  },
  {
    id: "dialogs",
    title: "Dialogs and destructive confirmation",
    group: "Surfaces",
    workspaces: everyWorkspace,
    classification: "standardize",
    current: "Settings, rename, move, share, media-info and nested review/transcript dialogs already use the app's rounded dark surfaces and modal-focus tooling. Close controls, action ordering, scrims and local dismissal wiring still differ.",
    proposed: "Review one dialog frame contract, preserving specialized content and current data flows. Define title, close target, initial focus, cancel behavior and destructive confirmation before adopting any shared wrapper.",
    sources: [
      { path: "src/hooks/use-modal-focus.ts", note: "Existing focus trap/restore behavior." },
      { path: "src/components/RenameDialog.tsx", note: "Small form dialog with editable content." },
      { path: "src/components/ShareDialog.tsx", note: "More complex sharing/export choices." },
      { path: "src/components/review/PasteNotesModal.tsx", note: "Nested review workflow, not just top-level components." },
      { path: "src/components/transcript/SpeakerRosterModal.tsx", note: "Nested identity-editing modal." },
    ],
    rules: [
      "Keep the 12px dialog tier distinct from 10px anchored surfaces.",
      "Trap focus while open and restore it when dismissed.",
      "Use explicit cancel and destructive labels; preserve second-click armed deletion where intentional.",
      "Do not substitute a modal for a simple inline action or disclosure.",
    ],
  },
  {
    id: "tables",
    title: "Library tables and selectable rows",
    group: "Content",
    workspaces: ["Home", "Library", "Transcripts"],
    classification: "keep",
    current: "Library, web, frames and session/history views share substantial table infrastructure. Existing work keeps stripes and column rules continuous below the last item, clips long cells, and provides violet selection. Cards, lasso selection and tree navigation are related but separate structures.",
    proposed: "Keep the established table language and use it as the catalog baseline. Demonstrate long Size/Date/title values, empty rows, selected rows, keyboard focus and right-edge alignment before considering any new table abstraction.",
    sources: [
      { path: "src/components/LibraryBrowserPane.tsx", note: "Shared shelf/table layout." },
      { path: "src/components/LibraryListRow.tsx", note: "Local-file row structure." },
      { path: "src/components/ClipTagIndicator.tsx", note: "Adopted passive Finder dot/stripe, used directly in isolated fixtures." },
      { path: "src/components/LibraryCard.tsx", note: "Clip caption dot beneath artwork; not the source of tag identity." },
      { path: "src/lib/finder-tags.ts", note: "Existing seven-color Finder palette and primary-tag selection." },
      { path: "src/components/WebListRows.tsx", note: "Web-source table rows." },
      { path: "src/components/FrameListRows.tsx", note: "Frame table rows." },
      { path: "src/styles/library.css", note: "Column, stripe, hover and selection geometry." },
    ],
    rules: [
      "Preserve column boundaries and empty-floor stripes rather than restoring older broken variants.",
      "Clip Finder tags use an 8px caption dot or a 2px far-left stripe inset 4px; preserve native tags, folder tints and violet selection. Full tag names remain accessible.",
      "Clip or ellipsize long cell content without hiding the row's actions.",
      "Multi-selection is not a collection of aria-current items.",
      "Keep existing files, frames, transcript associations and session history intact.",
    ],
  },
  {
    id: "panels",
    title: "Panels, drawers and detached windows",
    group: "Surfaces",
    workspaces: ["Library", "Clip", "Review", "Transcripts", "Settings", "Detached"],
    classification: "standardize",
    current: "The app has resizable sidebars, a multi-tab drawer, setup/NDI rails, transcript panels and an independent detached root. They share tokens but have different header/action spacing. Detached notice Dismiss references cp-btn, which currently has no CSS definition.",
    proposed: "Review common panel-header, divider, empty-state and overflow recipes while preserving each panel's purpose. Treat detached windows as first-class contexts, not copies that inherit the main window's dimensions by assumption.",
    sources: [
      { path: "src/components/QueueDrawer.tsx", note: "Shared docked/detached tab content and message adapter boundary." },
      { path: "src/PanelApp.tsx", note: "Detached root and unstyled cp-btn notice dismissal." },
      { path: "src/components/NdiInputPanel.tsx", note: "Gear-launched source settings dialog, separate from the persistent Preview stage and notes rail." },
      { path: "src/components/TranscriptReader.tsx", note: "Reader split-pane controls." },
      { path: "src/styles/resize.css", note: "Resize behavior is not ordinary button styling." },
    ],
    rules: [
      "Keep a single persistent player; panel layout must not determine source lifetime.",
      "Test narrow, docked, detached and theater contexts independently.",
      "Preserve drafts, tab state and floating-panel messages across layout changes.",
      "A catalog preview must never create a real room or connect a source.",
    ],
  },
  {
    id: "feedback",
    title: "Feedback, empty states and progress",
    group: "Content",
    workspaces: everyWorkspace,
    classification: "standardize",
    current: "CanvasToast already has explicit dismissal and a hover-paused countdown. Loading, empty, warning, disconnected and durable-note states live in several panels and media overlays. A shared color alone cannot distinguish progress from a saved outcome.",
    proposed: "Keep the toast behavior and document separate feedback recipes for transient confirmation, actionable error, empty guidance, progress and persistent stale media. Show honest note-delivery states and retain the last valid picture during a stall.",
    sources: [
      { path: "src/components/CanvasToast.tsx", note: "Explicit dismissal and remaining-time accounting." },
      { path: "src/components/NdiInputPanel.tsx", note: "Connection, missing runtime, stale source and recovery feedback." },
      { path: "src/components/ReviewPanel.tsx", note: "Note delivery, composer and source-specific guidance." },
      { path: "src/components/LogsPanel.tsx", note: "Longer-lived job feedback and technical detail." },
      { path: "src/styles/base.css", note: "Shared empty-state vocabulary." },
    ],
    rules: [
      "Say what happened and what the user can do next.",
      "Do not report synced until durable acknowledgement supports that state.",
      "Keep persistent errors or stale input visible until resolved or explicitly dismissed.",
      "Do not make the whole toast an accidental dismiss target.",
    ],
  },
  {
    id: "typography",
    title: "Typography, color and motion roles",
    group: "Content",
    workspaces: everyWorkspace,
    classification: "keep",
    current: "The app ships one Nunito Sans family, five loaded weights and an existing token scale. Neutral emphasis, violet selection, white focus and semantic feedback are established. Some role comments and component choices still disagree, including button tracking and small-heading treatments.",
    proposed: "Keep the installed type and palette. Catalog body, metadata, control, section, dialog and timecode roles using current tokens; review the few disputed mappings without replacing the scale or rounding every spacing value.",
    sources: [
      { path: "src/styles/tokens.css", note: "Type, weight, spacing, radius, elevation and motion tokens." },
      { path: "src/styles/base.css", note: "Base font, neutral accent, marker and focus declarations." },
      { path: "docs/DESIGN.md", note: "Current app rules; catalog proposals require review before adoption." },
      { path: "src/lib/design-tokens-contract.test.ts", note: "Existing token checks do not prove every visual role is consistent." },
    ],
    rules: [
      "Do not add fonts, dependencies, palette synonyms or unused production tokens for a catalog.",
      "Use only loaded weights; keep numeric readouts stable and verify them with the actual font.",
      "Separate selected, success, live, danger and identity roles before choosing color.",
      "Retain intentional 2px density rhythm; no blanket 4px spacing conversion.",
    ],
  },
  {
    id: "participants",
    title: "People, presenter and attention states",
    group: "Review",
    workspaces: ["Review"],
    classification: "keep",
    current: "Approved People fix: only the picture clips. The 72px rail keeps a 48px avatar, an external presenter pin and separate status slots. Compact camera/mic icons and controls are hidden; full device truth and actions remain in participant details and the room toolbar. Expanded and theater tiles retain device controls.",
    proposed: "Corrected production recipes are the main source-markup fixtures. Frozen historical clipping appears only under Before the fix. Preserve member identity, camera/microphone callbacks and parity across compact, expanded and theater layouts; no broader People redesign is implied.",
    sources: [
      { path: "src/components/PeoplePanel.tsx", note: "Participant identity, role, media state and controls." },
      { path: "src/styles/room.css", note: "Adopted image-only mask, presenter pin, status slots and compact/strip geometry; reused directly in fixtures." },
      { path: "src/App.tsx", note: "Theater and main PeoplePanel receive the same presenter and self-device truth." },
      { path: "src/components/PeoplePanel.test.tsx", note: "Production callback, keyboard and cross-variant behavior checks." },
    ],
    rules: [
      "Use member identity, not display name, as the participant key.",
      "Clipping is a functional defect, not a decorative variant to preserve.",
      "Never place full text badges or two device buttons inside the 48px circular image mask.",
      "Every variant must expose the same presenter/device truth and keyboard-accessible actions.",
    ],
  },
  {
    id: "preview",
    title: "Preview source and transport roles",
    group: "Review",
    workspaces: ["Clip", "Review", "Detached"],
    classification: "keep",
    current: "Approved Preview fix: passive sharing status and centered sequence-timecode availability above the unobstructed picture; playback/timing messages together below. Source settings and audio recovery belong in the NDI dialog, opened by the gear beside the single volume control. File playback and shared notes keep their existing behavior.",
    proposed: "The corrected production recipes are the main example, with separate disabled, focus, expanded and narrow specimens. Historical mixed vocabulary is collapsed under Before the fix. Broader catalog commands remain unadopted; connecting, privately previewing and sharing remain distinct actions.",
    sources: [
      { path: "src/App.tsx", note: "Persistent Monitor integration and Premiere sourceControls action." },
      { path: "src/components/Monitor.tsx", note: "Shared mounted picture surface." },
      { path: "src/components/Transport.tsx", note: "Playback/readout/utility responsibilities." },
      { path: "src/components/NdiPreviewHeader.tsx", note: "Production component: sharing and unavailable sequence timecode outside the picture." },
      { path: "src/components/AvidNdiSetup.tsx", note: "Production passive Avid setup disclosure in the shared NDI gear dialog; compatibility is separately verified." },
      { path: "src/components/ObsCaptureControls.tsx", note: "Exact application/window/crop controls inside the same gear dialog. Catalog uses static source markup; native discovery remains outside the catalog." },
      { path: "src/components/ObsBroadcastControls.tsx", note: "Explicit native-owned NDI broadcast; separate from preview and room sharing." },
      { path: "src/styles/ndi-preview-header.css", note: "Flow layout keeps the timecode centered without picture overlays." },
      { path: "src/styles/transport.css", note: "Adopted content-sized passive source-status recipe, separate from numeric timecode." },
      { path: "src/styles/buttons.css", note: "Adopted 26px neutral toolbar disclosure; no .btn-compact uppercase treatment." },
      { path: "src/components/NdiInputPanel.tsx", note: "Discovery, explicit source selection, connection and share flow." },
      { path: "src/components/SourceShareMenu.tsx", note: "Source actions remain reachable in narrow layouts." },
    ],
    rules: [
      "Live and sharing are passive statuses; the NDI gear opens source settings. Sequence timecode stays explicitly unavailable until verified.",
      "Use the production source-status and toolbar-disclosure classes; do not replace them with the generic catalog Button or StatusBadge.",
      "Private preview does not publish, host a room or request conversation devices.",
      "A live source disables file-seek/range behavior without borrowing a hidden file's time.",
      "Preserve monitor identity, last-frame retention and source ownership across workspace changes.",
    ],
  },
  {
    id: "async",
    title: "Asynchronous and branded actions",
    group: "Controls",
    workspaces: ["Clip", "Transcripts", "Settings", "Dialogs", "Detached"],
    classification: "intentional exception",
    current: "StatefulButton composes real job phase, stable-width layers and result announcements. Generate has a branded animated treatment; Export has a larger violet treatment. These are purposeful exceptions, although some CSS comments still describe retired green-primary behavior.",
    proposed: "Keep existing job ownership and branded recipes in the catalog. Review idle, loading, success, error and disabled states before deciding whether their visual frame can later compose the standard Button; do not remove their meaning in a blanket cleanup.",
    sources: [
      { path: "src/components/StatefulButton.tsx", note: "Parent-owned job phase, announcements and result reset timing." },
      { path: "src/components/GenerateButton.tsx", note: "Signature generation action." },
      { path: "src/components/Sidebar.tsx", note: "Export/Generate action placement and real job wiring." },
      { path: "src/styles/buttons.css", note: "Async layers, reduced motion, Generate and Export exceptions." },
    ],
    rules: [
      "A catalog simulates phase locally and never invokes an export or media job.",
      "Preserve fixed action width, aria-busy and outcome announcements.",
      "Style changes must not restart jobs or change their completion callbacks.",
      "Keep purposeful brand exceptions explicit rather than treating all gradients as drift.",
    ],
  },
  {
    id: "navigation",
    title: "App navigation, shelves and breadcrumbs",
    group: "Navigation",
    workspaces: ["Home", "Library", "Clip", "Review", "Transcripts", "Settings"],
    classification: "keep",
    current: "NavRail supplies primary workspace navigation. Library shelves, folder trees and reader breadcrumbs provide local location; the Review setup history action routes to Library sessions instead of maintaining a second history shelf. These are not ordinary command-button variants.",
    proposed: "Keep the current navigation hierarchy. Catalog selected, focused, expanded and unavailable states separately, using concise text and icons without moving Preview responsibilities into Clip or duplicating session history.",
    sources: [
      { path: "src/components/NavRail.tsx", note: "Primary workspace navigation and current-view state." },
      { path: "src/components/LibraryTree.tsx", note: "Folder hierarchy and disclosure behavior." },
      { path: "src/components/LibraryBrowserBar.tsx", note: "Shelf location, breadcrumbs and local actions." },
      { path: "src/components/CoReviewLobby.tsx", note: "Session-history navigation intent." },
      { path: "src/components/LibraryBrowser.tsx", note: "Library session/history destination." },
    ],
    rules: [
      "Keep global navigation distinct from tabs, local filters and commands.",
      "Opening Review must not reset the mounted player or local preview.",
      "Keep one authoritative session-history destination, including when no folders exist.",
      "Expose hierarchy, current location and disclosure state without relying on color alone.",
    ],
  },
];
