import { useState } from "react";
import { IconCamera, IconRefresh, IconCircleX as IconX, IconPlay, IconCheck, IconAlert } from "../src/components/Icons";
import { Button } from "./Button";
import { IconButton } from "./IconButton";
import { StatusBadge } from "./StatusBadge";
import { Comparison } from "./Comparison";
import { StatefulButton } from "../src/components/StatefulButton";
import type { ExampleProps } from "./example-types";

export function CommandExamples({ kind, state, size }: ExampleProps) {
  const [message, setMessage] = useState("All actions are local demonstrations.");
  const [job, setJob] = useState<"idle" | "busy" | "success" | "error">("idle");
  const common = { size, disabled: state === "disabled" || state === "busy", "aria-busy": state === "busy", "data-preview-state": state };
  const oldSize = size === "compact" ? " btn-compact" : "";
  if (kind === "statuses") return <Comparison current={<div className="cp-ds-stack"><div className="cp-ds-inline"><span className="cp-ds-current-status">Live</span><span className="cp-ds-current-status">Saved locally</span><span className="cp-ds-current-status">Waiting to sync</span></div><small>Source status, delivery status, and actions currently use overlapping treatments.</small></div>} proposed={<div className="cp-ds-stack"><div className="cp-ds-inline"><StatusBadge tone="live">Live</StatusBadge><StatusBadge tone="success">Synced</StatusBadge><StatusBadge tone="neutral">Saved locally</StatusBadge><StatusBadge tone="warning">Waiting to sync</StatusBadge><StatusBadge tone="danger">Disconnected</StatusBadge></div><small>Passive labels. No button border, hover effect, or tab stop.</small></div>} />;
  if (kind === "icons") return <Comparison current={<div className="cp-ds-inline"><button className="btn-icon" type="button" aria-label="Current refresh" onClick={() => setMessage("Refresh demonstrated.")}><IconRefresh size={13} /></button><button className="cp-icon-btn" type="button" aria-label="Current snapshot" onClick={() => setMessage("Snapshot demonstrated.")}><IconCamera size={15} /></button><button className="cp-room-bar-btn" type="button" aria-label="Current room action" onClick={() => setMessage("Room action demonstrated.")}><IconPlay size={13} /></button><span className="cp-ds-caption">Command, transport utility, room control</span></div>} proposed={<div className="cp-ds-stack"><div className="cp-ds-inline"><IconButton {...common} label="Refresh sources" onClick={() => setMessage("Refresh demonstrated. No discovery was started.")}><IconRefresh size={14} /></IconButton><IconButton {...common} label="Take snapshot" onClick={() => setMessage("Snapshot demonstrated. No media was accessed.")}><IconCamera size={14} /></IconButton><IconButton {...common} variant="quiet" label="Close example" onClick={() => setMessage("Close demonstrated.")}><IconX size={14} /></IconButton></div><small role="status">{message}</small></div>} />;
  if (kind === "async") return <Comparison same currentBasis="component" proposedBasis="mixed" current={<div className="cp-ds-stack">
    <div className="cp-ds-inline" style={{ width: "100%" }}><StatefulButton className="btn btn-primary cp-export-cta cp-sbtn-export" phase="idle" idleContent="Export clip" loadingLabel="Exporting…" onClick={() => setMessage("Export appearance only. No export was started.")} /></div>
    <StatefulButton className="btn btn-ghost cp-sbtn-fetch" phase="idle" idleContent="Fetch" loadingLabel="" onClick={() => setMessage("Fetch appearance only. No URL was requested.")} />
    <small>{message}</small><small>The actual Generate component has its own Specialty entry.</small>
  </div>} proposed={<div className="cp-ds-stack">
    <div className="cp-ds-inline" style={{ width: "100%" }}><StatefulButton className="btn btn-primary cp-export-cta cp-sbtn-export" phase={job === "busy" ? "loading" : job} idleContent="Export clip" loadingLabel="Exporting…" onClick={() => setJob("busy")} /></div>
    <StatefulButton className="btn btn-ghost cp-sbtn-fetch" phase={job === "busy" ? "loading" : job} idleContent="Fetch" loadingLabel="" onClick={() => setJob("busy")} />
    <div className="cp-ds-inline"><Button size={size} disabled={job === "busy"} onClick={() => setJob("busy")}>Simulate job</Button>{job === "busy" && <Button size={size} onClick={() => setJob("idle")}>Cancel</Button>}<StatusBadge tone={job === "error" ? "danger" : job === "success" ? "success" : "neutral"}>{job === "idle" ? "Ready" : job === "busy" ? "In progress" : job === "success" ? "Completed" : "Could not complete"}</StatusBadge></div>
    <div className="cp-ds-inline"><Button variant="quiet" size="compact" onClick={() => setJob("success")}><IconCheck size={13} />Show success</Button><Button variant="quiet" size="compact" onClick={() => setJob("error")}><IconAlert size={13} />Show error</Button><Button variant="quiet" size="compact" onClick={() => setJob("idle")}>Reset</Button></div>
    <small>Fixture controls above select real component phases. Export stays 36px; Fetch stays width-locked. No work is started and results remain visible for inspection.</small>
  </div>} />;
  return <Comparison current={<div className="cp-ds-stack"><div className="cp-ds-inline"><button className={`btn btn-primary${oldSize}`} type="button" disabled={state === "disabled"} onClick={() => setMessage("Primary action demonstrated.")}>Start session</button><button className={`btn${oldSize}`} type="button" onClick={() => setMessage("Secondary action demonstrated.")}>Refresh</button><button className={`btn btn-ghost${oldSize}`} type="button" onClick={() => setMessage("Disclosure demonstrated.")}>Premiere…</button></div><small>Current compact size also changes case, tracking, and radius.</small></div>} proposed={<div className="cp-ds-stack"><div className="cp-ds-inline"><Button {...common} variant="primary" onClick={() => setMessage("Start session demonstrated. No room was created.")}>{state === "busy" ? "Starting…" : "Start session"}</Button><Button {...common} onClick={() => setMessage("Refresh demonstrated.")}>Refresh</Button><Button {...common} variant="quiet" onClick={() => setMessage("Disclosure demonstrated.")}>Premiere…</Button><Button {...common} variant="quiet" tone="danger" onClick={() => setMessage("Destructive appearance demonstrated. Nothing was removed.")}>Remove</Button></div><small role="status">{message}</small><small>Same vocabulary at both sizes. Danger is intent, not a fourth hierarchy level.</small></div>} />;
}
