import { useId, useState } from "react";
import { Button } from "./Button";
import { Comparison } from "./Comparison";
import { ExpectedSpeakersMenu } from "../src/components/ExpectedSpeakersMenu";
import type { ExampleProps } from "./example-types";

export function FieldExamples({ kind, size, state }: ExampleProps) {
  const uid = useId();
  const [value, setValue] = useState("Sequence 01");
  const [invalid, setInvalid] = useState(false);
  const [choice, setChoice] = useState("File");
  const [enabled, setEnabled] = useState(false);
  const [speakerCount, setSpeakerCount] = useState(2);
  if (kind === "selects") return <Comparison proposedBasis="mixed" current={<div className="cp-ds-stack"><label className="cp-ds-field">Preview quality<select className="cp-select" defaultValue="480p"><option>480p</option><option>720p</option><option>1080p</option></select></label><small>Shared native selects remain the default for other fields.</small></div>} proposed={<div className="cp-ds-stack"><label className="cp-ds-field">Preview quality<select className={`cp-select${size === "compact" ? " sm" : ""}`} disabled={state === "disabled"} defaultValue="480p"><option>480p</option><option>720p</option><option>1080p</option></select></label><h3>Expected speakers · adopted violet selection</h3><div className="cp-ds-inline"><span>Expected speakers</span><ExpectedSpeakersMenu value={speakerCount} disabled={state === "disabled"} onChange={setSpeakerCount} /></div><small>Production component, isolated count only. Arrow keys, Home/End, Enter and Escape; the selected option uses Novella deep violet. Other native selects are unchanged.</small></div>} />;
  if (kind === "choices") return <Comparison current={<div className="cp-ds-stack"><label className="cp-ds-check"><input type="checkbox" defaultChecked />Local monitoring</label><div className="cp-ds-inline"><button className="btn" type="button" onClick={() => setChoice("File")}>File</button><button className="btn" type="button" onClick={() => setChoice("Premiere")}>Premiere</button></div><small>Current choice families vary in both treatment and semantics.</small></div>} proposed={<div className="cp-ds-stack"><fieldset className="cp-ds-fieldset"><legend>Program source</legend><div className="cp-ds-choice-group">{["File", "Premiere"].map((option) => <label key={option} data-selected={choice === option}><input type="radio" name={`${uid}-source`} value={option} checked={choice === option} onChange={() => setChoice(option)} />{option}</label>)}</div></fieldset><div className="cp-ds-inline"><button className="cp-ds-switch" type="button" role="switch" aria-checked={enabled} aria-label="Local program monitoring" onClick={() => setEnabled(!enabled)}><span /></button><span>Local program monitoring</span><small>{enabled ? "On" : "Off"}</small></div><small>A choice, a switch, and an action are different controls.</small></div>} />;
  return <Comparison current={<div className="cp-ds-stack"><label className="cp-ds-field">Filename<input className="cp-input" defaultValue="Sequence 01" /></label><label className="cp-ds-field">Session name<input className="cp-colobby-input" defaultValue="Sequence 01" /></label><small>Current fields use 30px and 32px recipes with different type sizes.</small></div>} proposed={<div className="cp-ds-stack"><label className="cp-ds-field" htmlFor={`${uid}-name`}>Session name</label><input className="cp-ds-input" data-density={size} id={`${uid}-name`} value={value} disabled={state === "disabled"} aria-invalid={invalid} aria-describedby={`${uid}-help${invalid ? ` ${uid}-error` : ""}`} onChange={(e) => { setValue(e.target.value); setInvalid(e.target.value.trim().length === 0); }} /><small id={`${uid}-help`}>Use a name your reviewers will recognize.</small>{invalid && <p className="cp-ds-error" role="alert" id={`${uid}-error`}>Enter a session name.</p>}<Button size="compact" variant="quiet" onClick={() => { setInvalid(!invalid); if (!invalid) setValue(""); else setValue("Sequence 01"); }}>{invalid ? "Restore valid field" : "Show validation error"}</Button><small>Visible label, associated help, and announced validation. No saved data.</small></div>} />;
}
